/**
 * lib/prompts/bathroom.js — Bathroom prompts (all 16 styles, English, hyperrealistic)
 */
export const BATHROOM_PROMPTS = {
  moderno_brasileiro: `Hyperrealistic professional photograph of a Brazilian contemporary modern bathroom with mid-to-high-end market appeal. A vanity cabinet in MDF with white or light grey lacquer finish, matte or satin, with 2-4 flat straight doors and 2-3 stacked drawers on one side, slim flush-mounted handles (no visible handle) or brushed metal bar handles, integrated toeboard base — no visible feet. A white or light grey marble countertop with fine veining (Carrara or similar) or marbleized porcelain, with a 3cm visible edge thickness and a rectangular undermount white ceramic basin. A tall straight-spout single-lever faucet in matte black or brushed chrome, mounted on the countertop. A large rectangular mirror with slightly rounded corners and a thin champagne, rose gold, or matte black metal frame, centered above the vanity, covering most of the wall. No integrated shelf. A modern white toilet with straight-line coupled flush box design, positioned on the plumbing wall. Accessories: a matte black or stainless steel soap dispenser on the countertop, a beige or light grey folded hand towel on the vanity or on a brushed metal towel bar wall-mounted, a small slim vase with a eucalyptus or fern sprig on the countertop. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  popular_brasileiro: `Hyperrealistic professional photograph of a Brazilian popular-market bathroom staged with affordable standard fixtures. A compact vanity cabinet in white MDF/particleboard with standard popular market finish (no lacquer, no high-gloss) — 2 flat straight doors plus 1 central or upper drawer, simple chrome bar handles one per door, base with short visible feet or simple toeboard, 60-80cm width proportional to the bathroom. A white formica or simple white ceramic countertop with a white ceramic vessel basin (round or rectangular) positioned ON TOP of the countertop — not undermounted. A chrome single-lever faucet, basic standard model, mounted on the basin or countertop. A simple rectangular frameless mirror OR a mirror with small white MDF frame with a small lower shelf, standard size (50x70cm or similar), no rounded corners, no decorative frame. A standard white toilet with coupled flush box, basic model, positioned on the plumbing wall. A white plastic or white ceramic soap dispenser on the vanity. One folded white towel on a simple chrome towel rack wall-mounted. No candles, no diffusers, no plants. All furniture must be MDF/particleboard with standard popular market finish — no lacquer, no high-gloss, no premium materials. Hardware exclusively basic chrome. No granite, marble, or terrazzo countertops. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  minimalista_clean: `Hyperrealistic professional photograph of a Brazilian minimalist bathroom. A floating clean-lined cumaru wood vanity. A modern white ceramic vessel sink. A transparent frameless glass shower enclosure. Minimal matte black faucet fixtures. White towels folded and organized on a rack. A single small succulent plant. Sharp, clean geometric lines. Spa-like serene atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  aconchegante_natural: `Hyperrealistic professional photograph of a Brazilian cozy natural bathroom. Warm beige travertine tiles on walls and floor. A wooden vanity with natural finish and soft lighting. A rounded white ceramic sink. Woven basket storage with rolled towels. Small plants on the counter. Warm sconce lighting with fabric shades. A natural fiber bath mat. Comfortable, warm, inviting spa atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  luxo_contemporaneo: `Hyperrealistic professional photograph of a Brazilian luxury contemporary bathroom. Large high-gloss white marble tiles on walls and floor. A floating white marble vanity with gold hardware. Modern-design gold faucet fixtures. A large mirror with integrated LED lighting. A frameless glass shower with marble interior. Luxury spa-quality white towels. Sophisticated, elegant atmosphere. Bright ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  industrial_urbano: `Hyperrealistic professional photograph of a Brazilian industrial urban bathroom. A black metal vanity with concrete-look laminate countertop. A white ceramic vessel sink. Industrial pipe shelving with towels. Matte black fixtures and hardware throughout. Edison bulb lighting above the mirror. Urban, edgy atmosphere. Natural lighting through a frosted window. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  boho_brasileiro: `Hyperrealistic professional photograph of a Brazilian boho bathroom. Colorful geometric-patterned cement tiles on the floor. A rustic wooden vanity with woven basket storage. A hand-painted ceramic sink with details. A round rattan mirror. Hanging and surface plants throughout. Colorful towels with tassels. Macrame accents. Relaxed, eclectic bohemian atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  classico_atemporal: `Hyperrealistic professional photograph of a Brazilian classic timeless bathroom. Traditional-layout white subway tiles on walls. A traditional mahogany vanity cabinet with marble countertop. A classic white porcelain pedestal sink. A traditional wood-framed mirror. Vintage-style brass fixtures. Classic hotel-style white towels. Elegant, traditional atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  rustico_brasileiro: `Hyperrealistic professional photograph of a Brazilian rustic bathroom. A robust natural-finish cumaru wood vanity. An earthy-toned ceramic vessel sink. A natural stone-look countertop. Matte black wrought iron fixtures. A reclaimed wood mirror frame. Earthy palette of brown, beige, and stone tones. Dominant textured materials in the furniture. Warm, natural atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  colonial_brasileiro: `Hyperrealistic professional photograph of a Brazilian colonial-style bathroom. A carved-detail jacaranda wood vanity cabinet. A white classical marble countertop. Gold-finish vintage brass fixtures. An ornate carved wood framed mirror. White towels with lace details. Blue and white Portuguese ceramic decorative accessories. Elegant classical proportions. Warm, traditional atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  contemporaneo_colorido: `Hyperrealistic professional photograph of a Brazilian contemporary colorful bathroom. White subway tile base walls. Vibrant-colored geometric terrazzo accent wall in the shower area. Modern gold faucet fixtures and hardware. Organized colorful yellow and blue ceramic accessories. A modern vanity with white marble countertop. A round geometric mirror. Playful, sophisticated atmosphere. Bright natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  japandi_brasileiro: `Hyperrealistic professional photograph of a Brazilian Japandi bathroom. Natural light wood tiles on floor and walls. A minimalist light-finish floating wooden vanity. A simple white ceramic vessel sink. A large frameless round mirror. Minimal matte black fixtures. Bamboo accents and plants. Rolled white towels. Zen spa wabi-sabi atmosphere. Soft diffused natural lighting. Neutral palette of wood and white. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  art_deco_brasileiro: `Hyperrealistic professional photograph of a Brazilian Art Deco bathroom. Black and white chevron-pattern geometric floor tiles. A black lacquer Art Deco vanity with brass details. An octagonal mirror with brass frame. Vintage Deco-style brass fixtures. A black marble countertop. Brass and frosted glass Art Deco wall sconces. Glamorous 1930s atmosphere. Warm ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  escandinavo_tropical: `Hyperrealistic professional photograph of a Brazilian Scandinavian tropical bathroom. Clean simple white wall tiles. A minimalist floating light wood vanity. An integrated white ceramic sink. Large tropical plants in the bathroom. A simple round mirror. Minimalist white fixtures. Simple white towels. Bright, airy hygge-tropical atmosphere. Abundant natural lighting through a frosted window. Palette of white, wood, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  neo_mediterraneo: `Hyperrealistic professional photograph of a Brazilian neo-Mediterranean bathroom. A traditional white ceramic pedestal sink. Blue Mediterranean ceramic accessories. A white-framed mirror. A natural fiber basket with towels. Coastal, relaxed atmosphere. Bright natural lighting. Palette of white, blue, and terracotta tones in the decor. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  urban_jungle: `Hyperrealistic professional photograph of a Brazilian urban jungle bathroom. A floating wooden vanity with plants on the counter. Multiple plants of various sizes on shelves and hanging. A white ceramic sink. Natural fiber accessories. A green, spa-like oasis atmosphere. Bright natural lighting filtered through plants. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,
}
