/**
 * lib/prompts/bedroom.js — Bedroom prompts (all 16 styles, English, hyperrealistic)
 */
export const BEDROOM_PROMPTS = {
  moderno_brasileiro: `Hyperrealistic professional photograph of a Brazilian contemporary modern bedroom with mid-to-high-end market appeal. A fitted wardrobe in MDF combining white or light grey lacquer doors and wood-laminate modules (freijo or light oak), sliding doors preferably, with slim brushed metal or brass handles, floor-to-ceiling height. A queen or king size bed with an upholstered box base in light grey or beige fabric, a tall upholstered headboard in linen with discreet linear stitching in grey or beige. Bedding in neutral tones — white, pearl grey, beige — hotel-quality cotton sheets, a soft-textured duvet, pillows with smooth and subtle geometric pattern cases. Floating wall-mounted nightstands or floor nightstands with one drawer in white MDF or wood-tone matching the wardrobe, each with a table lamp with gold or copper metal base and a white or beige fabric shade. A rectangular medium-pile rug in light grey, beige, or off-white positioned under the bed with visible edges on the sides. Optionally: a low dresser in white MDF with brushed metal handles, or a minimalist vanity with a round mirror in a metallic gold or black frame. Clean contemporary lines throughout. No rustic furniture, no excessive gold, no frosted mirrors. Aesthetic of a decorated model apartment from a mid-to-high-end Brazilian developer. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  popular_brasileiro: `Hyperrealistic professional photograph of a Brazilian popular-market bedroom staged with affordable standard furniture. A large wardrobe in white MDF/particleboard with standard popular market finish (no lacquer, no high-gloss, no wood-grain laminate). Choose the option that best fits the available wall space: Option A — sliding wardrobe with 3-4 sliding doors in plain white MDF with simple horizontal grooves, with or without upper aerial modules, chrome bar handles. Option B — wardrobe with drawers and doors: module with 5 stacked drawers on one side and 2-door module on the other, all in standard white MDF, chrome bar handles. Option C — compact set: 2-door wardrobe in standard white or black MDF plus matching 4-drawer dresser, both with simple chrome bar handles. Position flush against the longest uninterrupted wall that does NOT contain any window or door — NEVER place a wardrobe in front of or adjacent to a window. A queen or double bed with a box base upholstered in dark grey or charcoal fabric, basic standard. Simple upholstered headboard in dark grey or integrated with the wardrobe. Bedding: white or light beige sheet, grey or taupe duvet, two simple pillows. Optionally if space allows: a small white MDF nightstand with one drawer, basic model, with a simple table lamp on top. All furniture must be MDF/particleboard with standard popular market finish — no lacquer, no high-gloss, no solid wood or freijo structure. No designer brand references or premium products. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  minimalista_clean: `Hyperrealistic professional photograph of a Brazilian minimalist bedroom. A low-profile centered cumaru wood platform bed. Clean-textured white linen bedding. Symmetrical minimal floating wooden nightstands. Simple geometric pendant lights hanging above. Sheer white curtains at windows. Neutral palette of beige, grey, and white. Very few decorative objects. Calm, serene, peaceful atmosphere. Soft natural lighting. Organized, clean space. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  aconchegante_natural: `Hyperrealistic professional photograph of a Brazilian cozy natural bedroom. Warm honey-tone jatoba wood flooring. A soft-textured beige linen upholstered headboard. Wooden nightstands with natural finish and warm-light table lamps. Layered cream and beige bedding with a knit throw blanket. A plush wool area rug under the bed. Indoor plants on the nightstand. Soft, warm ambient lighting. Comfortable, homey, inviting atmosphere. Soft golden natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  luxo_contemporaneo: `Hyperrealistic professional photograph of a Brazilian luxury contemporary bedroom. Large format white marble-effect porcelain floor tiles. A king-size grey velvet tufted upholstered bed frame. White marble nightstands with gold hardware. Crystal table lamps with white shades. Luxurious white bedding with gold accent pillows. A modern-design statement chandelier. Abstract art above the headboard. Sophisticated, elegant atmosphere. Soft ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  industrial_urbano: `Hyperrealistic professional photograph of a Brazilian industrial urban bedroom. A black metal bed frame with a reclaimed wood headboard. Industrial metal nightstands with Edison bulb lamps. Simple grey linen-textured bedding. Metal floating shelves with books. Urban, edgy atmosphere. Natural lighting through the window. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  boho_brasileiro: `Hyperrealistic professional photograph of a Brazilian boho bedroom. Natural light wood flooring. A low platform bed with colorful layered textiles. A large macrame headboard wall hanging. Rattan nightstands with warm lighting. Colorful patterned layered rugs. Various hanging and surface plants. Dreamcatcher and ethnic textile decorations. Warm ambient string lights. Relaxed, eclectic bohemian atmosphere. Soft warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  classico_atemporal: `Hyperrealistic professional photograph of a Brazilian classic timeless bedroom. Polished dark espresso wood flooring. A beige linen upholstered bed with a classic tufted headboard. Traditional mahogany nightstands with carved details. Classic table lamps with fabric shades. Elegant white bedding with subtle embroidery. A traditional-pattern area rug in muted colors. Subtle white wall moldings. Elegant, understated atmosphere. Soft warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  rustico_brasileiro: `Hyperrealistic professional photograph of a Brazilian rustic bedroom. A robust, natural-finish centered solid wood platform bed. Natural beige-toned textured linen bedding. Symmetrical wrought iron wall sconces. A rough-textured natural stone side table. A traditional woven area rug in earthy tones. Earthy palette of brown, terracotta, and beige. Warm, inviting, cozy atmosphere. Pronounced visible textured materials in the furniture. Soft warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  colonial_brasileiro: `Hyperrealistic professional photograph of a Brazilian colonial-style bedroom. A centered jacaranda wood four-poster bed with carved details. Symmetrical traditional-design cane bedside tables. An ornate classical carved wood headboard. Delicate white Portuguese lace bedding. Framed religious art above the headboard. Dominant warm dark wood tones. A small classical brass chandelier above the bed. Traditional, elegant atmosphere. Warm soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  contemporaneo_colorido: `Hyperrealistic professional photograph of a Brazilian contemporary colorful bedroom. Clean white base walls. A textured grey fabric upholstered headboard. Vibrant throw pillows in yellow, blue, and emerald arranged on the bed. Bold geometric colorful Brazilian art above the headboard. Modern-design gold metal nightstands. A small geometric-pattern area rug under the bed. An eclectic mix of modern furniture. Playful, sophisticated atmosphere. Bright natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  japandi_brasileiro: `Hyperrealistic professional photograph of a Brazilian Japandi bedroom. Natural blonde light cumaru flooring. A minimalist low platform bed with beige linen bedding. Minimal light wood floating wooden nightstands. Paper lantern pendant lights with soft glow. A single monstera plant in the corner. A tatami-inspired mat beside the bed. Sheer white curtains. Zen, calm, wabi-sabi atmosphere. Soft diffused natural lighting. Neutral palette of beige and grey. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  art_deco_brasileiro: `Hyperrealistic professional photograph of a Brazilian Art Deco bedroom. A navy blue velvet upholstered bed with brass details. Mirrored geometric nightstands with brass trim. Brass Art Deco table lamps with frosted glass. Luxurious jewel-toned bedding with geometric patterns. A geometric mirror with gold frame above the headboard. Glamorous, sophisticated 1940s atmosphere. Warm ambient lighting from Art Deco fixtures. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  escandinavo_tropical: `Hyperrealistic professional photograph of a Brazilian Scandinavian tropical bedroom. White-washed light ash wood flooring. A simple light wood platform bed with white linen bedding. Minimal light-finish wooden nightstands. Tropical monstera and palm plants on the nightstand. Bright clean white walls. A simple minimal white pendant light. Airy hygge atmosphere with a tropical touch. Abundant soft natural lighting. Palette of white, beige, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  neo_mediterraneo: `Hyperrealistic professional photograph of a Brazilian neo-Mediterranean bedroom. Smooth plaster white textured walls. Natural warm terracotta floor tiles. A white linen bed with blue accent pillows. Light weathered wood nightstands. Blue and white ceramic table lamps. An arched window with sheer white curtains. Woven basket storage. Relaxed coastal vacation atmosphere. Bright soft natural lighting. Palette of white, blue, and terracotta. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  urban_jungle: `Hyperrealistic professional photograph of a Brazilian urban jungle bedroom. Natural light wood flooring. A simple grey platform bed with white bedding. Abundant plants of various sizes surrounding the bed. Plant stands beside the bed with monstera. Botanical prints above the headboard. Hanging plants in macrame holders. A jute natural fiber rug. A lush, peaceful green sanctuary atmosphere. Bright natural lighting filtered through plants. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,
}
