/**
 * lib/prompts/dining-room.js — Dining Room prompts (all 16 styles, English, hyperrealistic)
 */
export const DINING_ROOM_PROMPTS = {
  moderno_brasileiro: `Hyperrealistic professional photograph of a Brazilian contemporary modern dining room. Rich warm-toned ipe wood flooring. A centered oval organic-form wood dining table with glass insert. Sculptural curved leather and cane dining chairs around the table. A sculptural pendant light fixture above the table. A low-profile mid-century wood sideboard. Abundant warm natural lighting. Sensual furniture curves. Inviting atmosphere. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  popular_brasileiro: `Hyperrealistic professional photograph of a Brazilian popular-market dining room staged with affordable standard furniture. A rectangular dining table with an 8mm tempered glass top on a white or black standard MDF/particleboard base. Four to six chairs upholstered in dark grey or black synthetic suede fabric with MDF/particleboard structure matching the table, simple chrome feet or handles. Simple synthetic fabric curtains in white or cream tone on a basic chrome or PVC rod at every visible window. Optionally: a low buffet in white MDF/particleboard with 4 straight doors and chrome bar handles, or a standard display cabinet with glass shelves and doors, both in popular market standard. Optionally: a simple pendant light above the table, basic chrome or white model with a plastic or simple fabric shade. All furniture must be MDF/particleboard with standard popular market finish — no lacquer, no high-gloss, no premium materials. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  minimalista_clean: `Hyperrealistic professional photograph of a Brazilian minimalist dining room. A centered minimal rectangular wood and glass dining table. Six modern clean-lined chairs around the table. A single centered geometric-design pendant light above the table. Very few decorative objects — ceramic vases only. Neutral palette of beige, grey, and white. Organized, clean space. Abundant natural lighting through windows. Serene atmosphere. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  aconchegante_natural: `Hyperrealistic professional photograph of a Brazilian cozy natural dining room. Warm honey-tone jatoba wood flooring. A centered round wooden dining table with natural finish. Comfortable beige linen upholstered chairs around the table. A warm pendant light with fabric shade above the table. A wooden sideboard with family photos. A natural-tone wool area rug under the table. Warm, homey, inviting atmosphere. Soft golden natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  luxo_contemporaneo: `Hyperrealistic professional photograph of a Brazilian luxury contemporary dining room. Large high-gloss white marble floor tiles. A centered designer white marble-top dining table. Elegant grey velvet upholstered chairs around the table. A modern crystal statement chandelier above the table. Large abstract art on the wall. A contemporary gold metal sideboard. Sophisticated, elegant atmosphere. Bright natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  industrial_urbano: `Hyperrealistic professional photograph of a Brazilian industrial urban dining room. A centered industrial reclaimed wood dining table with metal legs. Black metal chairs with wood seats around the table. Industrial Edison bulb pendant lights above the table. Metal shelving with dishes and plants. Urban, edgy atmosphere. Natural lighting through windows. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  boho_brasileiro: `Hyperrealistic professional photograph of a Brazilian boho dining room. Natural light wood flooring. A rustic wooden dining table with mix-and-match colorful chairs. Woven rattan chairs. A pendant light in woven natural fibers above the table. A colorful ethnic-patterned table runner. Plants on the sideboard and hanging. A macrame wall hanging. Relaxed, eclectic bohemian atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  classico_atemporal: `Hyperrealistic professional photograph of a Brazilian classic timeless dining room. Polished dark espresso wood flooring. A centered traditional rectangular mahogany dining table. Beige upholstered dining chairs with carved wood details around the table. A traditional brass and crystal chandelier above the table. A traditional mahogany sideboard cabinet. A traditional-pattern area rug in muted colors. Elegant, understated, formal atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  rustico_brasileiro: `Hyperrealistic professional photograph of a Brazilian rustic dining room. A centered massive reclaimed cumaru solid wood dining table. Robust wooden chairs with leather seats around the table. A centered black wrought iron chandelier above the table. A reclaimed wood buffet cabinet. A traditional woven area rug in earthy tones. Dominant earthy palette of brown, terracotta, and beige. Pronounced textured materials in the furniture. Warm, inviting, cozy atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  colonial_brasileiro: `Hyperrealistic professional photograph of a Brazilian colonial-style dining room. A centered large traditional rectangular jacaranda wood dining table. Six symmetrically positioned cane-back dining chairs around the table. A traditional carved wood buffet cabinet with blue and white Portuguese ceramic decorative plates displayed on top. A centered classical crystal chandelier above the table. Elegant, balanced classical proportions. Dominant warm dark wood tones. Inviting, formal atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  contemporaneo_colorido: `Hyperrealistic professional photograph of a Brazilian contemporary colorful dining room. Bright white base walls. A centered modern white marble-top dining table. Vibrant-colored upholstered dining chairs in a mix of yellow, blue, and orange around the table. A modern gold metal pendant light above the table. Bold colorful Brazilian art on the wall. A modern-design geometric sideboard. Eclectic, sophisticated atmosphere. Abundant bright natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  japandi_brasileiro: `Hyperrealistic professional photograph of a Brazilian Japandi dining room. Natural light cumaru wood flooring. A centered minimalist low-profile wooden dining table. Simple clean-lined wooden chairs around the table. A single paper lantern pendant light above the table. A minimal low wooden sideboard. A single statement monstera plant in the corner. Neutral palette of beige, grey, and wood. Zen, calm, serene atmosphere. Soft diffused natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  art_deco_brasileiro: `Hyperrealistic professional photograph of a Brazilian Art Deco dining room. Dark wood Art Deco-pattern geometric parquet flooring. A centered black lacquer dining table with brass inlay details. Emerald green velvet dining chairs with brass legs around the table. A geometric brass and frosted glass chandelier above the table. A mirrored Art Deco sideboard with brass trim. Geometric mirror wall decoration. Glamorous 1930s atmosphere. Warm ambient lighting from Art Deco fixtures. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  escandinavo_tropical: `Hyperrealistic professional photograph of a Brazilian Scandinavian tropical dining room. White-washed light ash wood flooring. A centered simple light-finish wooden dining table. Simple white Scandinavian-design chairs around the table. A simple minimal white pendant light above the table. Large tropical plants in the corners. Bright white walls. A minimalist light wood sideboard. Airy hygge atmosphere with tropical plants. Abundant natural lighting. Palette of white, wood, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  neo_mediterraneo: `Hyperrealistic professional photograph of a Brazilian neo-Mediterranean dining room. A centered weathered white-finish wooden dining table. Simple white chairs with blue cushions around the table. A white and blue ceramic pendant light above the table. Natural woven placemats. Blue and white Mediterranean ceramic vases as centerpiece. Coastal, relaxed, vacation atmosphere. Abundant bright natural lighting. Palette of white, blue, and terracotta tones in the decor. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  urban_jungle: `Hyperrealistic professional photograph of a Brazilian urban jungle dining room. Natural light wood flooring. A simple wooden dining table with a plant centerpiece. Modern grey chairs around the table. Abundant plants of various sizes on shelves and floor. Hanging plants above the table area. Botanical prints on the walls. A natural fiber rug under the table. A green dining oasis atmosphere. Bright natural lighting through plants. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,
}
