/**
 * lib/prompts/kitchen.js — Kitchen prompts (all 16 styles, English, hyperrealistic)
 */
export const KITCHEN_PROMPTS = {
  moderno_brasileiro: `Hyperrealistic professional photograph of a Brazilian contemporary modern kitchen with mid-to-high-end market appeal. Fitted modular cabinets in medium grey matte MDF (urban grey) with flush-mounted integrated handles (no visible handle) or slim brushed metal handles. Structure and details in wood laminate (freijo or light oak). Complete configuration: upper wall cabinets with flat grey matte doors close to the ceiling, with an open niche clad in wood laminate with recessed LED strip lighting on the underside displaying small decorative objects; lower base cabinets with grey matte doors and drawers with integrated or slim handles; a tall pantry tower integrated into the set in grey matte. A white or light grey marble countertop with fine veining (Carrara marble or similar) or marbleized porcelain — premium appearance, 3-4cm visible edge thickness. Backsplash in white marble or marbleized porcelain matching the countertop — no colorful tiles. Appliances: a French-door or side-by-side refrigerator in brushed stainless steel positioned at the side or end of the cabinets; a 4-5 burner gas cooktop built into the countertop in stainless steel; a built-in microwave or electric oven in a dedicated cabinet niche in stainless steel or black; a slim range hood or exhaust above the cooktop in stainless steel or black. Accessories: two or three decorative objects in the wood niche — small vases, cookbooks, or glass jars with spices; a slim vase with a green sprig on the countertop; do not overcrowd the scene. Aesthetic of a planned kitchen in a decorated model apartment from a mid-to-high-end Brazilian developer. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  popular_brasileiro: `Hyperrealistic professional photograph of a Brazilian popular-market kitchen staged with affordable standard cabinetry. A complete set of modular kitchen cabinets in MDF/particleboard, standard popular market finish (no lacquer, no high-gloss). Choose the option that best harmonizes with the existing walls and floor: Option A — White with relief-panel doors (more traditional/popular): all doors (base cabinets, upper wall cabinets, and tall pantry) in white MDF with decorative relief panel, curved line motif with diamond detail in the center, chrome bar handles, stainless steel or light grey laminate countertop, backsplash in colorful Portuguese tiles (blue, yellow, and white) or plain white tile. Option B — Freijo wood-tone plus matte black (more modern popular): doors in standard matte black MDF (no lacquer) with structure and sides in freijo laminate (MDF with wood laminate, not solid wood), chrome or brushed nickel bar handles, freijo laminate countertop (wood-tone formica), background: white wall or plain white tile. Mandatory appliances for both options: a standard white frost-free refrigerator positioned at one end of the cabinet set; a white countertop or niche microwave; a white 4-burner floor-standing stove with oven, positioned in the cooking area if visible. Accessories: a small vase with a simple plant or basic flowers on the countertop; do not overcrowd the scene. All cabinets must be MDF/particleboard standard popular — no lacquer, no high-gloss, no premium materials. Consistent handles throughout the kitchen (all chrome OR all brushed nickel, never mixed). No marble or natural stone countertops. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  minimalista_clean: `Hyperrealistic professional photograph of a Brazilian minimalist kitchen. Smooth polished grey concrete floor. White matte handleless floating cabinets. An ultra-thin white quartz countertop with integrated sink. Exposed concrete ceiling detail. Minimal black matte faucet hardware and fixtures. A single succulent plant on the windowsill. A simple geometric pendant light. Sharp, clean, organized lines. Soft diffused natural lighting. Neutral palette of white and grey. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  aconchegante_natural: `Hyperrealistic professional photograph of a Brazilian cozy natural kitchen. Warm honey-tone light oak wood flooring. Natural-finish shaker-style wood cabinets. A honed beige granite countertop with warm texture. A warm-pattern terracotta tile backsplash. Vintage-style brass fixtures. Woven baskets on storage shelves. Potted herbs on the windowsill. Warm pendant lights with fabric shades. Comfortable, homey, inviting atmosphere. Soft golden natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  luxo_contemporaneo: `Hyperrealistic professional photograph of a Brazilian luxury contemporary kitchen. Polished dark grey large-format porcelain floor tiles. Floor-to-ceiling dark grey matte cabinets. A white Calacatta marble countertop with dramatic veining. Premium-finish gold hardware and fixtures. A modern sculptural statement chandelier. Integrated panel-ready high-end appliances. A visible wine cooler. Sophisticated, elegant atmosphere. Bright ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  industrial_urbano: `Hyperrealistic professional photograph of a Brazilian industrial urban kitchen. Black metal cabinets with open shelving. Industrial-finish concrete-look laminate countertop. White subway tiles in brick-pattern backsplash. Matte black fixtures and hardware throughout. Hanging Edison bulb pendant lights. Stainless steel appliances. Urban, edgy atmosphere. Natural lighting through windows. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  boho_brasileiro: `Hyperrealistic professional photograph of a Brazilian boho kitchen. Natural light wood flooring. Olive green painted lower base cabinets. Upper open wood shelving with colorful dishes. A colorful Moroccan-patterned cement tile backsplash. A warm butcher-block wooden countertop. Vintage brass fixtures. Woven natural fiber pendant lights. Various plants, hanging and on the counter. Relaxed, eclectic bohemian atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  classico_atemporal: `Hyperrealistic professional photograph of a Brazilian classic timeless kitchen. Polished dark espresso wood flooring. Traditional-design white shaker-style cabinets. A polished black granite countertop. A classic white subway tile backsplash. Elegant vintage brass hardware. Traditional pendant lights with glass shades. A white porcelain farmhouse sink. Elegant, understated atmosphere. Warm soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  rustico_brasileiro: `Hyperrealistic professional photograph of a Brazilian rustic kitchen. Natural-texture reclaimed cumaru wood flooring. Natural-texture reclaimed demolition wood cabinets. A dark grey soapstone (pedra-sabao) natural stone countertop. A terracotta exposed brick backsplash. Aged-patina copper fixtures and hardware. A hanging wrought iron pot rack. Visible wooden ceiling beams. Earthy palette of brown, stone, and copper. Pronounced textured materials. Warm, cozy atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  colonial_brasileiro: `Hyperrealistic professional photograph of a Brazilian colonial-style kitchen. Rich-finish dark jacaranda wood flooring. Traditional carved-detail jacaranda wood cabinets. An elegant veined white marble countertop. Traditional blue and white Portuguese azulejo tile backsplash. Vintage colonial gold brass fixtures. A small classical crystal chandelier. Carved wood details on the island. Warm, inviting traditional atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  contemporaneo_colorido: `Hyperrealistic professional photograph of a Brazilian contemporary colorful kitchen. Large-format white porcelain floor tiles. Modern navy blue matte-finish cabinets. A white terrazzo countertop with colorful aggregate. Modern brushed gold hardware. Vibrant-pattern colorful geometric backsplash tiles. Modern-design gold pendant lights. Organized colorful yellow and blue accessories. Playful, sophisticated atmosphere. Bright natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  japandi_brasileiro: `Hyperrealistic professional photograph of a Brazilian Japandi kitchen. Natural blonde light ash wood flooring. Minimal handleless floating light wood cabinets. A matte-finish beige stone countertop. A simple white tile backsplash. Minimalist matte black fixtures. A few wabi-sabi-style ceramic pieces. Bamboo cutting boards. A single plant in the corner. Zen, calm, clean atmosphere. Soft diffused natural lighting. Neutral palette of wood and beige. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  art_deco_brasileiro: `Hyperrealistic professional photograph of a Brazilian Art Deco kitchen. Dark wood geometric-pattern parquet flooring. High-gloss black lacquer cabinets with gold trim. A black marble countertop with gold veining. A black, white, and gold geometric-pattern tile backsplash. Vintage Art Deco-design brass fixtures. Brass and frosted glass geometric pendant lights. Gold hardware throughout. Glamorous, sophisticated 1930s atmosphere. Warm ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  escandinavo_tropical: `Hyperrealistic professional photograph of a Brazilian Scandinavian tropical kitchen. White-washed light ash wood flooring. Simple clean Scandinavian-design white cabinets. A minimalist light wood countertop. A simple white subway tile backsplash. Minimalist white fixtures. Tropical plants on the windowsill and counter. Simple minimal white pendant lights. Airy hygge atmosphere with tropical plants. Abundant bright natural lighting. Palette of white, wood, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  neo_mediterraneo: `Hyperrealistic professional photograph of a Brazilian neo-Mediterranean kitchen. White shaker-style painted cabinets. A textured white countertop. Blue Mediterranean-pattern ceramic tile backsplash. Decorative blue ceramic accessories. Weathered-finish wooden open shelving. Coastal, relaxed, vacation-vibe atmosphere. Abundant bright natural lighting. Palette of white, blue, and terracotta tones in the decor. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  urban_jungle: `Hyperrealistic professional photograph of a Brazilian urban jungle kitchen. Natural light wood flooring. Dark green matte-finish lower cabinets. Upper open wood shelving filled with plants. A simple white countertop. A white subway tile backsplash. Abundant plants on the counter and hanging in various sizes. Botanical prints on the walls. Wooden cutting boards and natural accessories. A lush green oasis atmosphere. Bright natural lighting filtered through plants. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,
}
