/**
 * lib/prompts/living-room.js — Living Room prompts (all 16 styles, English, hyperrealistic)
 */
export const LIVING_ROOM_PROMPTS = {
  moderno_brasileiro: `Hyperrealistic professional photograph of a Brazilian contemporary modern living room with mid-to-high-end market appeal. A low-profile, wide sofa in light beige or off-white upholstery with clean horizontal lines and low backrest, accented by decorative cushions in contrasting tones — terracotta, graphite grey, moss green, and beige — mixing smooth and subtle geometric textures. No tufting. No excessively wide armrests. A small round side table in dark metal (matte black or graphite) next to the sofa, thin and minimalist. A rectangular low-pile rug in neutral tone — beige, light grey, or off-white — centered under the sofa area. A floating or floor-standing TV console in MDF combining white lacquer and a wood-toned niche (freijo or walnut) with recessed LED strip lighting inside the niche. A flat-screen TV wall-mounted or on the console. ONLY if there is a clearly large open area far from any corridor, passage, or transition between rooms: a small rectangular white table with thin legs in metal or wood, two to four chairs with grey upholstered seats and geometric structure, and a pendant light with brass/gold rods and transparent glass globes above the table. If no such area exists, omit the dining set entirely. A medium-large plant in a white ceramic or concrete pot, placed in a corner or at the transition between areas. Abundant warm natural lighting. Clean contemporary lines throughout. No rustic furniture, no excessive tufting, no gaudy gold. Aesthetic of a decorated model apartment from a mid-to-high-end Brazilian developer. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  popular_brasileiro: `Hyperrealistic professional photograph of a Brazilian popular-market living room staged with affordable standard furniture. A large L-shaped or straight reclining sofa upholstered in synthetic suede fabric in brown, caramel, or dark beige, with tufted backrest stitching, wide square armrests, and a recliner or chaise module positioned according to room layout. A rectangular low-pile rug in light grey or off-white centered under the sofa set. A rectangular coffee table in white or off-white MDF/particleboard with standard market finish (no lacquer, no high-gloss), simple model with lower shelf or closed base, positioned in front of the sofa. A TV stand or buffet in white MDF/particleboard, standard popular market style — flat straight doors, small drawers, simple chrome bar handles. A flat-screen TV on the stand or wall-mounted above it. Optionally: a simple floor lamp in metal or plastic with a basic white shade next to the sofa. Optionally: a medium plant in a simple plastic or basic ceramic pot in a room corner. All wooden furniture must be MDF/particleboard with standard popular market finish — no lacquer, no high-gloss, no premium materials. No designer brand references or premium products. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  minimalista_clean: `Hyperrealistic professional photograph of a Brazilian minimalist living room. Polished smooth concrete exposed ceiling, cumaru wood floor planks with natural finish. A large grey sectional sofa with clean lines positioned 40cm from walls. A white rectangular marble coffee table centered. A minimal floating TV console in cumaru wood. Very few decorative objects — white ceramic vases only. A single monstera plant in a corner ceramic pot. Sheer white floor-to-ceiling curtains at windows. Abundant soft natural lighting. Neutral palette of beige, grey, and white. Organized, serene space. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  aconchegante_natural: `Hyperrealistic professional photograph of a Brazilian cozy natural living room. Warm jatoba wood flooring with honey tones. A comfortable beige linen sofa with textured throw pillows. A wooden coffee table with natural finish and books on top. A plush cream wool area rug under the furniture. Warm table lamps with fabric shades providing soft lighting. Indoor plants of various sizes in ceramic pots. Wooden shelving with family photos. Soft natural linen curtains. Warm, homey, inviting atmosphere. Soft golden natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  luxo_contemporaneo: `Hyperrealistic professional photograph of a Brazilian luxury contemporary living room. Large format white marble-effect porcelain floor tiles. A sophisticated grey velvet designer sectional sofa. A black marble coffee table with gold metal base. A modern sculptural statement chandelier. Large colorful abstract art canvas on the wall. Gold metal accent furniture details throughout. Sheer curtains at existing windows. Sophisticated, elegant atmosphere. Abundant bright natural lighting. Visible high-end finishes. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  industrial_urbano: `Hyperrealistic professional photograph of a Brazilian industrial urban living room. A vintage brown distressed leather sofa positioned centrally. A reclaimed wood coffee table with industrial metal legs. Black metal shelving with books and plants. Hanging Edison bulb pendant lights. A vintage metal factory accent chair. Urban, edgy atmosphere. Natural lighting through windows. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  boho_brasileiro: `Hyperrealistic professional photograph of a Brazilian boho living room. Natural light wood flooring. A rattan sectional sofa with colorful ethnic-patterned cushions. A low Moroccan-style wooden coffee table. Layered colorful rugs with geometric patterns. A large macrame wall hanging. Abundant plants of various sizes, both hanging and floor-standing. Woven storage baskets. Decorative warm string lights. An eclectic mix of textures and colors. Relaxed bohemian atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  classico_atemporal: `Hyperrealistic professional photograph of a Brazilian classic timeless living room. Polished dark espresso-finish wood flooring. An elegant beige linen sofa with rolled arms. A traditional mahogany coffee table with centered design. Symmetrically placed classic upholstered armchairs. A traditional Persian-style area rug in muted colors. Subtle white wall moldings. Classic table lamps with fabric shades. Elegant, understated atmosphere. Warm, soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  rustico_brasileiro: `Hyperrealistic professional photograph of a Brazilian rustic living room. A large, robust solid wood sofa with brown leather cushions. A massive centered reclaimed wood coffee table. A wrought iron floor lamp in the corner. A traditional woven area rug in earthy tones. Earthy palette of brown, beige, and terracotta. Dominant textured materials in the furniture. Warm, inviting, cozy atmosphere. Soft natural lighting. Handcrafted furniture quality visible. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  colonial_brasileiro: `Hyperrealistic professional photograph of a Brazilian colonial-style living room. Dark, rich-finish jacaranda wood furniture. Austrian-style cane-back armchairs symmetrically positioned. A solid wood coffee table with carved details. Balanced, elegant classical proportions. A carved wood console table with framed art above it. A traditional Persian-style area rug in muted tones. Dominant warm dark wood tones. Traditional, inviting atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  contemporaneo_colorido: `Hyperrealistic professional photograph of a Brazilian contemporary colorful living room. White marble floor with geometric terrazzo inserts. A clean-base modern grey sectional sofa. Vibrant throw pillows in yellow, orange, emerald, and blue arranged on the sofa. A gold metal accent side table. Bold, colorful Brazilian abstract art on the walls. A geometric-pattern area rug under the coffee table. An eclectic mix of modern furniture and classic Brazilian pieces. Bright white walls. Sophisticated yet playful atmosphere. Abundant natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  japandi_brasileiro: `Hyperrealistic professional photograph of a Brazilian Japandi living room. Light cumaru wood flooring in natural blonde tone. A low-profile beige linen sofa with clean lines. A minimalist low wooden coffee table with subtle grain. A tatami-inspired natural fiber area rug. A single large statement monstera plant in a ceramic pot. Sheer white floor-to-ceiling curtains. A few wabi-sabi ceramic pieces. Zen, calm, serene atmosphere. Soft diffused natural lighting. Neutral palette of beige, grey, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  art_deco_brasileiro: `Hyperrealistic professional photograph of a Brazilian Art Deco living room. An emerald green velvet sofa with gold metal legs. An octagonal marble coffee table with brass details. A sunburst-design geometric mirror with gold frame. A brass floor lamp with frosted glass shade. Rich jewel tones of emerald, navy, and gold in the furniture and decor. Glamorous, sophisticated 1940s-inspired atmosphere. Warm ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  escandinavo_tropical: `Hyperrealistic professional photograph of a Brazilian Scandinavian tropical living room. Light white-washed ash wood flooring. A white linen sofa with simple clean lines. A minimalist light wood coffee table. Abundant tropical plants — monstera, banana leaf — in various sizes. Bright white walls. A beige jute natural fiber rug. A simple white pendant light. Airy, open atmosphere blending hygge with tropical warmth. Abundant bright natural lighting. Neutral warm palette of white, beige, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  neo_mediterraneo: `Hyperrealistic professional photograph of a Brazilian neo-Mediterranean living room. A white linen sofa with blue striped cushions. A light weathered-finish wood coffee table. Blue and white Mediterranean ceramic vases. Natural woven baskets. Billowing sheer white curtains. Relaxed coastal atmosphere with vacation vibes. Abundant bright natural lighting. Palette of white, blue, and terracotta tones in the decor. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  urban_jungle: `Hyperrealistic professional photograph of a Brazilian urban jungle living room. Natural light wood flooring. A modern grey sofa with a simple base. Abundant plants filling the space in various sizes — monstera, fiddle leaf fig, ferns, and hanging plants. Plant stands at various heights in wood and metal. Botanical prints on the walls. A jute natural fiber rug. Macrame plant hangers. A lush green oasis atmosphere. Bright natural lighting filtering through the plants. Palette of grey, green, white, and natural tones. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,
}
