/**
 * lib/prompts/office.js — Office prompts (all 16 styles, English, hyperrealistic)
 */
export const OFFICE_PROMPTS = {
  moderno_brasileiro: `Hyperrealistic professional photograph of a Brazilian contemporary modern home office with mid-to-high-end market appeal. A wide desk with a white MDF lacquer or wood-laminate top (freijo or light oak), 3-4cm visible edge thickness, on matte black or brushed steel metal legs. A separate pedestal drawer unit with 3-4 drawers in white or light grey MDF lacquer with slim brushed metal or flush-mounted handles, on casters for mobility. A high-back ergonomic chair in dark grey or black mesh or fabric, upholstered seat, chrome or polished aluminum base with casters — contemporary slim design without excessive bulk. If wall space is available: a fitted shelf unit in MDF combining open niches and closed modules with swing doors in white or grey lacquer, slim brushed metal handles, ceiling height, open niches with color-organized books, small vases, and decorative objects. A flat-screen monitor on the desk (one or two monitors), slim keyboard and wireless mouse, a metal monitor arm or stand, a discreet cable management box under the desk. A desk lamp articulated with a base or clamp, in matte black or gold metal, positioned at one corner of the desktop. Optionally: a suspended pendant over the desk with a metal arm and minimalist shade. A small plant in a white ceramic or concrete pot on the desk or shelf. An abstract framed artwork on the wall behind the desk. Metal or concrete pen holder and desk accessories. Organized books. Aesthetic of a planned home office in a decorated model apartment from a mid-to-high-end Brazilian developer. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  popular_brasileiro: `Hyperrealistic professional photograph of a Brazilian popular-market home office staged with affordable standard furniture. A rectangular desk in white or black standard MDF/particleboard with standard market finish (no lacquer, no high-gloss), simple model with a flat top, optionally with one lateral drawer or a separate MDF pedestal drawer unit. Simple chrome bar handles. A swivel executive office chair with high backrest, upholstered in black fabric or faux leather, black plastic or chrome metal base with casters, basic model with height adjustment. Optionally if space allows: a simple bookshelf in white MDF/particleboard with 3-5 open shelves, with organized books and one or two basic decorative objects. OR a tall cabinet in white MDF with 2 straight doors and chrome bar handles. A flat-screen desktop monitor on the desk (basic model), keyboard and mouse on the desktop. Do not overcrowd the scene with too many objects. All furniture must be MDF/particleboard with standard popular market finish — no lacquer, no high-gloss, no premium materials or designer brands. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  minimalista_clean: `Hyperrealistic professional photograph of a Brazilian minimalist home office. A floating white wall-mounted desk with clean lines. A minimalist black ergonomic mesh chair. Minimal white floating shelves with very few objects. A single succulent plant on the desk. A black geometric desk lamp. A large window with sheer curtains. Organized, clean workspace. Soft natural lighting. Neutral palette of white, grey, and black. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  aconchegante_natural: `Hyperrealistic professional photograph of a Brazilian cozy natural home office. Warm honey-tone jatoba wood flooring. A solid natural-finish wood desk with drawers. A comfortable beige fabric upholstered desk chair. A floor-to-ceiling wood bookshelf filled with books. A natural-tone wool area rug under the desk. A warm fabric-shade desk lamp. Plants on shelves and the desk. A window with linen curtains. Warm, inviting, productive atmosphere. Soft golden natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  luxo_contemporaneo: `Hyperrealistic professional photograph of a Brazilian luxury contemporary home office. A modern black lacquer desk with gold accents. A sophisticated black tufted leather executive chair. Floating shelves with gold brackets and art books. A modern sculptural gold statement desk lamp. A large abstract canvas art piece. Sophisticated, professional atmosphere. Bright ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  industrial_urbano: `Hyperrealistic professional photograph of a Brazilian industrial urban home office. An industrial reclaimed wood desk with metal pipe legs. A vintage distressed brown leather desk chair. Black metal shelving units with books and boxes. Hanging Edison bulb pendant lights. Vintage metal file cabinets. Urban, edgy, productive atmosphere. Natural lighting through windows. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  boho_brasileiro: `Hyperrealistic professional photograph of a Brazilian boho home office. Natural light wood flooring. A simple wood trestle-style desk. A natural woven rattan desk chair with a cushion. A large macrame wall hanging behind the desk. Open wood shelving with colorful books and plants. Woven storage baskets. A colorful patterned layered rug. Various hanging plants. Decorative warm string lights. Relaxed, creative, bohemian atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  classico_atemporal: `Hyperrealistic professional photograph of a Brazilian classic timeless home office. Polished mahogany dark wood flooring. A traditional mahogany desk with carved details and leather inset top. A classic dark brown tufted leather desk chair. A floor-to-ceiling built-in wood bookshelf with a ladder. A traditional brass desk lamp with a green glass shade. A traditional Persian-pattern area rug. Subtle white wall moldings. Elegant, formal, professional atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  rustico_brasileiro: `Hyperrealistic professional photograph of a Brazilian rustic home office. A massive reclaimed cumaru solid wood desk with iron legs. A rustic aged brown leather desk chair. Asymmetric reclaimed wood shelving with books. A matte black wrought iron desk lamp. Earthy palette of brown, stone, and iron. Dominant textured materials in the furniture. Warm, cozy, productive atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  colonial_brasileiro: `Hyperrealistic professional photograph of a Brazilian colonial-style home office. An ornate carved-detail antique jacaranda writing desk. An elegant colonial-style cane-back desk chair. A carved jacaranda bookshelf with glass doors. Blue and white Portuguese ceramic decorative objects on the desk and shelves. A small classical brass chandelier. Framed art on the wall. Warm, traditional, professional atmosphere. Warm soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  contemporaneo_colorido: `Hyperrealistic professional photograph of a Brazilian contemporary colorful home office. Clean bright white walls. A modern white desk with organized colorful accessories. A vibrant yellow modern ergonomic desk chair. A bold geometric colorful abstract mural on the wall behind the desk. White floating shelves with colorful books. A modern gold desk lamp. A geometric-pattern colorful area rug. Playful, creative, inspiring atmosphere. Bright natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  japandi_brasileiro: `Hyperrealistic professional photograph of a Brazilian Japandi home office. Natural blonde light cumaru wood flooring. A minimalist clean-lined light-finish wood desk. A natural wood wishbone chair with beige cushion. Very few decorative objects. A minimal floating wood shelf with a bonsai plant. A soft-glow paper lantern desk lamp. A tatami-inspired mat under the desk. Sheer white curtains at a large window. Zen, calm, wabi-sabi productive atmosphere. Soft diffused natural lighting. Neutral palette of beige and wood. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  art_deco_brasileiro: `Hyperrealistic professional photograph of a Brazilian Art Deco home office. Dark wood chevron-pattern geometric parquet flooring. A black lacquer desk with gold geometric inlay in Art Deco style. An emerald green velvet desk chair with brass legs. A geometric brass and glass bookshelf. A brass Art Deco desk lamp with a geometric frosted glass shade. A sunburst gold-frame geometric mirror. Rich jewel tones of black, green, and gold. Glamorous, sophisticated 1930s atmosphere. Warm ambient lighting from Art Deco fixtures. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  escandinavo_tropical: `Hyperrealistic professional photograph of a Brazilian Scandinavian tropical home office. White-washed light ash wood flooring. A simple white minimalist Scandinavian-design desk. A clean modern white ergonomic chair. A white pegboard wall organization system with plants. Tropical plants of various sizes on the desk and floor. Bright white walls. A simple minimal white desk lamp. Airy, hygge, productive atmosphere with a tropical touch. Abundant soft natural lighting. Palette of white, wood, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  neo_mediterraneo: `Hyperrealistic professional photograph of a Brazilian neo-Mediterranean home office. A simple weathered white-finish wooden desk. A simple white chair with a blue cushion. White floating shelves with books. Decorative blue ceramic accessories. A natural woven storage basket. Sheer curtains at the window. Coastal, relaxed, productive atmosphere. Abundant bright natural lighting. Palette of white, blue, and terracotta tones in the decor. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

  urban_jungle: `Hyperrealistic professional photograph of a Brazilian urban jungle home office. Natural light wood flooring. A simple wood desk with plants integrated on the surface. A modern grey ergonomic desk chair. Abundant large plants of various sizes on the desk, shelves, and hanging. Botanical prints and living walls. Natural wood shelving filled with plants and books. A lush, inspiring green workspace oasis atmosphere. Bright natural lighting filtered through plant leaves. Palette of wood, green, and white. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,
}
