/**
 * worker/lib/prompt-library.js
 *
 * Full prompt library for all 6 room types × 16 styles.
 * All styles inline — no external imports.
 * Format: long-form hyperrealistic English prompts, mirroring gira-chave-pro/lib/prompts/*.js
 *
 * NOTE: adaptPrompt() in services/ai.js strips the opening
 * "Hyperrealistic professional photograph of a Brazilian X room." sentence before
 * wrapping the furniture content in the editing task instruction.
 */

export const PROMPT_LIBRARY = {

  // ─────────────────────────────────────────────────────────────────────────
  // LIVING ROOM
  // ─────────────────────────────────────────────────────────────────────────
  living_room: {
    moderno_brasileiro: `Hyperrealistic professional photograph of a Brazilian contemporary modern living room with mid-to-high-end market appeal. A low-profile, wide sofa in light beige or off-white upholstery with clean horizontal lines and low backrest, accented by decorative cushions in contrasting tones — terracotta, graphite grey, moss green, and beige — mixing smooth and subtle geometric textures. No tufting. No excessively wide armrests. A small round side table in dark metal (matte black or graphite) next to the sofa, thin and minimalist. A rectangular low-pile rug in neutral tone — beige, light grey, or off-white — centered under the sofa area. A floating or floor-standing TV console in MDF combining white lacquer and a wood-toned niche (freijo or walnut) with recessed LED strip lighting inside the niche. A flat-screen TV wall-mounted or on the console. If the space allows an integrated dining area: a rectangular white table with thin legs in metal or wood, chairs with grey upholstered seats and geometric structure, and a pendant light with brass/gold rods and transparent glass globes above the table. A medium-large plant in a white ceramic or concrete pot, placed in a corner or at the transition between areas. Abundant warm natural lighting. Clean contemporary lines throughout. No rustic furniture, no excessive tufting, no gaudy gold. Aesthetic of a decorated model apartment from a mid-to-high-end Brazilian developer. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    popular_brasileiro: `Hyperrealistic professional photograph of a Brazilian popular-market living room staged with affordable standard furniture. A large L-shaped or straight reclining sofa upholstered in synthetic suede fabric in brown, caramel, or dark beige, with tufted backrest stitching, wide square armrests, and a recliner or chaise module positioned according to room layout. A rectangular low-pile rug in light grey or off-white centered under the sofa set. A rectangular coffee table in white or off-white MDF/particleboard with standard market finish (no lacquer, no high-gloss), simple model with lower shelf or closed base, positioned in front of the sofa. A TV stand or buffet in white MDF/particleboard, standard popular market style — flat straight doors, small drawers, simple chrome bar handles. A flat-screen TV on the stand or wall-mounted above it. Optionally: a simple floor lamp in metal or plastic with a basic white shade next to the sofa. Optionally: a medium plant in a simple plastic or basic ceramic pot in a room corner. All wooden furniture must be MDF/particleboard with standard popular market finish — no lacquer, no high-gloss, no premium materials. No designer brand references or premium products. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    minimalista_clean: `Hyperrealistic professional photograph of a Brazilian minimalist living room. Polished smooth concrete exposed ceiling, cumaru wood floor planks with natural finish. A large grey sectional sofa with clean lines positioned 40cm from walls. A white rectangular marble coffee table centered. A minimal floating TV console in cumaru wood. Very few decorative objects — white ceramic vases only. A single monstera plant in a corner ceramic pot. Sheer white floor-to-ceiling curtains at windows. Abundant soft natural lighting. Neutral palette of beige, grey, and white. Organized, serene space. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    aconchegante_natural: `Hyperrealistic professional photograph of a Brazilian cozy natural living room. Warm jatoba wood flooring with honey tones. A comfortable beige linen sofa with textured throw pillows. A wooden coffee table with natural finish and books on top. A plush cream wool area rug under the furniture. Warm table lamps with fabric shades providing soft lighting. Indoor plants of various sizes in ceramic pots. Wooden shelving with family photos. Soft natural linen curtains. Warm, homey, inviting atmosphere. Soft golden natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    luxo_contemporaneo: `Hyperrealistic professional photograph of a Brazilian luxury contemporary living room. Large format white marble-effect porcelain floor tiles. A sophisticated grey velvet designer sectional sofa. A black marble coffee table with gold metal base. A modern sculptural statement chandelier. Large colorful abstract art canvas on the wall. Gold metal accent furniture details throughout. Floor-to-ceiling windows with sheer curtains. Sophisticated, elegant atmosphere. Abundant bright natural lighting. Visible high-end finishes. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    industrial_urbano: `Hyperrealistic professional photograph of a Brazilian industrial urban living room. Exposed red terracotta brick wall with visible texture. Polished grey concrete floor. A vintage brown distressed leather sofa positioned centrally. A reclaimed wood coffee table with industrial metal legs. Black metal shelving with books and plants. Hanging Edison bulb pendant lights. A vintage metal factory accent chair. Large windows with black frames. Urban, edgy atmosphere. Natural lighting through industrial windows. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    boho_brasileiro: `Hyperrealistic professional photograph of a Brazilian boho living room. Natural light wood flooring. A rattan sectional sofa with colorful ethnic-patterned cushions. A low Moroccan-style wooden coffee table. Layered colorful rugs with geometric patterns. A large macrame wall hanging. Abundant plants of various sizes, both hanging and floor-standing. Woven storage baskets. Decorative warm string lights. An eclectic mix of textures and colors. Relaxed bohemian atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    classico_atemporal: `Hyperrealistic professional photograph of a Brazilian classic timeless living room. Polished dark espresso-finish wood flooring. An elegant beige linen sofa with rolled arms. A traditional mahogany coffee table with centered design. Symmetrically placed classic upholstered armchairs. A traditional Persian-style area rug in muted colors. Subtle white wall moldings. Classic table lamps with fabric shades. Elegant, understated atmosphere. Warm, soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    rustico_brasileiro: `Hyperrealistic professional photograph of a Brazilian rustic living room. Terracotta-colored exposed brick accent wall. Natural-finish cumaru wood ceiling beams visibly exposed. A large, robust solid wood sofa with brown leather cushions. A massive centered reclaimed wood coffee table. A wrought iron floor lamp in the corner. Pronounced natural stone feature wall texture. Earthy palette of brown, beige, and terracotta. Dominant textured materials. Warm, inviting, cozy atmosphere. Soft natural lighting. Handcrafted furniture quality visible. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    colonial_brasileiro: `Hyperrealistic professional photograph of a Brazilian colonial-style living room. Dark, rich-finish jacaranda wood furniture. Austrian-style cane-back armchairs symmetrically positioned. A solid wood coffee table with carved details. Blue and white Portuguese ceramic azulejo tiles on a feature wall. Balanced, elegant classical proportions. A carved wood console table with framed religious art above it. A visible lioz stone doorway arch. Dominant warm dark wood tones. Traditional, inviting atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    contemporaneo_colorido: `Hyperrealistic professional photograph of a Brazilian contemporary colorful living room. White marble floor with geometric terrazzo inserts. A clean-base modern grey sectional sofa. Vibrant throw pillows in yellow, orange, emerald, and blue arranged on the sofa. A gold metal accent side table. Bold, colorful Brazilian abstract art on the walls. A geometric-pattern area rug under the coffee table. An eclectic mix of modern furniture and classic Brazilian pieces. Bright white walls. Sophisticated yet playful atmosphere. Abundant natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    japandi_brasileiro: `Hyperrealistic professional photograph of a Brazilian Japandi living room. Light cumaru wood flooring in natural blonde tone. A low-profile beige linen sofa with clean lines. A minimalist low wooden coffee table with subtle grain. A tatami-inspired natural fiber area rug. A single large statement monstera plant in a ceramic pot. Sheer white floor-to-ceiling curtains. A few wabi-sabi ceramic pieces. Zen, calm, serene atmosphere. Soft diffused natural lighting. Neutral palette of beige, grey, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    art_deco_brasileiro: `Hyperrealistic professional photograph of a Brazilian Art Deco living room. Dark wood geometric chevron-pattern parquet flooring. An emerald green velvet sofa with gold metal legs. An octagonal marble coffee table with brass details. A sunburst-design geometric mirror with gold frame. A brass floor lamp with frosted glass shade. Subtle geometric-pattern Art Deco wallpaper. Rich jewel tones of emerald, navy, and gold. Glamorous, sophisticated 1940s-inspired atmosphere. Warm ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    escandinavo_tropical: `Hyperrealistic professional photograph of a Brazilian Scandinavian tropical living room. Light white-washed ash wood flooring. A white linen sofa with simple clean lines. A minimalist light wood coffee table. Abundant tropical plants — monstera, banana leaf — in various sizes. Bright white walls. A beige jute natural fiber rug. A simple white pendant light. Airy, open atmosphere blending hygge with tropical warmth. Abundant bright natural lighting. Neutral warm palette of white, beige, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    neo_mediterraneo: `Hyperrealistic professional photograph of a Brazilian neo-Mediterranean living room. White textured stucco-finish walls. Natural terracotta floor tiles. A white linen sofa with blue striped cushions. A light weathered-finish wood coffee table. A visible white arched doorway. Blue and white Mediterranean ceramic vases. Natural woven baskets. Billowing sheer white curtains. Relaxed coastal atmosphere with vacation vibes. Abundant bright natural lighting. Palette of white, blue, and terracotta. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    urban_jungle: `Hyperrealistic professional photograph of a Brazilian urban jungle living room. Natural light wood flooring. A modern grey sofa with a simple base. Abundant plants filling the space in various sizes — monstera, fiddle leaf fig, ferns, and hanging plants. Plant stands at various heights in wood and metal. Botanical prints on the walls. A jute natural fiber rug. Macrame plant hangers. A lush green oasis atmosphere. Bright natural lighting filtering through the plants. Palette of grey, green, white, and natural tones. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // BEDROOM
  // ─────────────────────────────────────────────────────────────────────────
  bedroom: {
    moderno_brasileiro: `Hyperrealistic professional photograph of a Brazilian contemporary modern bedroom with mid-to-high-end market appeal. A fitted wardrobe in MDF combining white or light grey lacquer doors and wood-laminate modules (freijo or light oak), sliding doors preferably, with slim brushed metal or brass handles, floor-to-ceiling height. A queen or king size bed with an upholstered box base in light grey or beige fabric, a tall upholstered headboard in linen with discreet linear stitching in grey or beige. Bedding in neutral tones — white, pearl grey, beige — hotel-quality cotton sheets, a soft-textured duvet, pillows with smooth and subtle geometric pattern cases. Floating wall-mounted nightstands or floor nightstands with one drawer in white MDF or wood-tone matching the wardrobe, each with a table lamp with gold or copper metal base and a white or beige fabric shade. A rectangular medium-pile rug in light grey, beige, or off-white positioned under the bed with visible edges on the sides. Optionally: a low dresser in white MDF with brushed metal handles, or a minimalist vanity with a round mirror in a metallic gold or black frame. Clean contemporary lines throughout. No rustic furniture, no excessive gold, no frosted mirrors. Aesthetic of a decorated model apartment from a mid-to-high-end Brazilian developer. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    popular_brasileiro: `Hyperrealistic professional photograph of a Brazilian popular-market bedroom staged with affordable standard furniture. A large wardrobe in white MDF/particleboard with standard popular market finish (no lacquer, no high-gloss, no wood-grain laminate). Choose the option that best fits the available wall space: Option A — sliding wardrobe with 3-4 sliding doors in plain white MDF with simple horizontal grooves, with or without upper aerial modules, chrome bar handles. Option B — wardrobe with drawers and doors: module with 5 stacked drawers on one side and 2-door module on the other, all in standard white MDF, chrome bar handles. Option C — compact set: 2-door wardrobe in standard white or black MDF plus matching 4-drawer dresser, both with simple chrome bar handles. Position flush against the main wall. A queen or double bed with a box base upholstered in dark grey or charcoal fabric, basic standard. Simple upholstered headboard in dark grey or integrated with the wardrobe. Bedding: white or light beige sheet, grey or taupe duvet, two simple pillows. Optionally if space allows: a small white MDF nightstand with one drawer, basic model, with a simple table lamp on top. All furniture must be MDF/particleboard with standard popular market finish — no lacquer, no high-gloss, no solid wood or freijo structure. No designer brand references or premium products. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    minimalista_clean: `Hyperrealistic professional photograph of a Brazilian minimalist bedroom. Polished grey concrete accent wall behind the bed. A low-profile centered cumaru wood platform bed. Clean-textured white linen bedding. Symmetrical minimal floating wooden nightstands. Simple geometric pendant lights hanging above. Sheer white curtains at windows. Neutral palette of beige, grey, and white. Very few decorative objects. Calm, serene, peaceful atmosphere. Soft natural lighting. Organized, clean space. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    aconchegante_natural: `Hyperrealistic professional photograph of a Brazilian cozy natural bedroom. Warm honey-tone jatoba wood flooring. A soft-textured beige linen upholstered headboard. Wooden nightstands with natural finish and warm-light table lamps. Layered cream and beige bedding with a knit throw blanket. A plush wool area rug under the bed. Indoor plants on the nightstand. Soft, warm ambient lighting. Comfortable, homey, inviting atmosphere. Soft golden natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    luxo_contemporaneo: `Hyperrealistic professional photograph of a Brazilian luxury contemporary bedroom. Large format white marble-effect porcelain floor tiles. A king-size grey velvet tufted upholstered bed frame. White marble nightstands with gold hardware. Crystal table lamps with white shades. Luxurious white bedding with gold accent pillows. A modern-design statement chandelier. Abstract art above the headboard. Sophisticated, elegant atmosphere. Soft ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    industrial_urbano: `Hyperrealistic professional photograph of a Brazilian industrial urban bedroom. Exposed brick accent wall behind the bed. Polished grey concrete floor. A black metal bed frame with a reclaimed wood headboard. Industrial metal nightstands with Edison bulb lamps. Simple grey linen-textured bedding. Metal floating shelves with books. A large window with a black metal frame. Urban, edgy atmosphere. Natural lighting through the industrial window. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    boho_brasileiro: `Hyperrealistic professional photograph of a Brazilian boho bedroom. Natural light wood flooring. A low platform bed with colorful layered textiles. A large macrame headboard wall hanging. Rattan nightstands with warm lighting. Colorful patterned layered rugs. Various hanging and surface plants. Dreamcatcher and ethnic textile decorations. Warm ambient string lights. Relaxed, eclectic bohemian atmosphere. Soft warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    classico_atemporal: `Hyperrealistic professional photograph of a Brazilian classic timeless bedroom. Polished dark espresso wood flooring. A beige linen upholstered bed with a classic tufted headboard. Traditional mahogany nightstands with carved details. Classic table lamps with fabric shades. Elegant white bedding with subtle embroidery. A traditional-pattern area rug in muted colors. Subtle white wall moldings. Elegant, understated atmosphere. Soft warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    rustico_brasileiro: `Hyperrealistic professional photograph of a Brazilian rustic bedroom. Natural-texture reclaimed cumaru wood accent wall behind the bed. A robust, natural-finish centered solid wood platform bed. Natural beige-toned textured linen bedding. Symmetrical wrought iron wall sconces. A rough-textured natural stone side table. Earthy palette of brown, terracotta, and beige. Warm, inviting, cozy atmosphere. Pronounced visible textured materials. Soft warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    colonial_brasileiro: `Hyperrealistic professional photograph of a Brazilian colonial-style bedroom. A centered jacaranda wood four-poster bed with carved details. Symmetrical traditional-design cane bedside tables. An ornate classical carved wood headboard. Delicate white Portuguese lace bedding. Framed religious art above the headboard. Dominant warm dark wood tones. A small classical brass chandelier above the bed. Traditional, elegant atmosphere. Warm soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    contemporaneo_colorido: `Hyperrealistic professional photograph of a Brazilian contemporary colorful bedroom. Clean white base walls. A textured grey fabric upholstered headboard. Vibrant throw pillows in yellow, blue, and emerald arranged on the bed. Bold geometric colorful Brazilian art above the headboard. Modern-design gold metal nightstands. A small geometric-pattern area rug under the bed. An eclectic mix of modern furniture. Playful, sophisticated atmosphere. Bright natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    japandi_brasileiro: `Hyperrealistic professional photograph of a Brazilian Japandi bedroom. Natural blonde light cumaru flooring. A minimalist low platform bed with beige linen bedding. Minimal light wood floating wooden nightstands. Paper lantern pendant lights with soft glow. A single monstera plant in the corner. A tatami-inspired mat beside the bed. Sheer white curtains. Zen, calm, wabi-sabi atmosphere. Soft diffused natural lighting. Neutral palette of beige and grey. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    art_deco_brasileiro: `Hyperrealistic professional photograph of a Brazilian Art Deco bedroom. Dark wood herringbone geometric parquet flooring. A navy blue velvet upholstered bed with brass details. Mirrored geometric nightstands with brass trim. Brass Art Deco table lamps with frosted glass. Luxurious jewel-toned bedding with geometric patterns. A gold and silver geometric-pattern accent wall wallpaper. Glamorous, sophisticated 1940s atmosphere. Warm ambient lighting from Art Deco fixtures. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    escandinavo_tropical: `Hyperrealistic professional photograph of a Brazilian Scandinavian tropical bedroom. White-washed light ash wood flooring. A simple light wood platform bed with white linen bedding. Minimal light-finish wooden nightstands. Tropical monstera and palm plants on the nightstand. Bright clean white walls. A simple minimal white pendant light. Airy hygge atmosphere with a tropical touch. Abundant soft natural lighting. Palette of white, beige, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    neo_mediterraneo: `Hyperrealistic professional photograph of a Brazilian neo-Mediterranean bedroom. Smooth plaster white textured walls. Natural warm terracotta floor tiles. A white linen bed with blue accent pillows. Light weathered wood nightstands. Blue and white ceramic table lamps. An arched window with sheer white curtains. Woven basket storage. Relaxed coastal vacation atmosphere. Bright soft natural lighting. Palette of white, blue, and terracotta. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    urban_jungle: `Hyperrealistic professional photograph of a Brazilian urban jungle bedroom. Natural light wood flooring. A simple grey platform bed with white bedding. Abundant plants of various sizes surrounding the bed. Plant stands beside the bed with monstera. Botanical prints above the headboard. Hanging plants in macrame holders. A jute natural fiber rug. A lush, peaceful green sanctuary atmosphere. Bright natural lighting filtered through plants. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // BATHROOM
  // ─────────────────────────────────────────────────────────────────────────
  bathroom: {
    moderno_brasileiro: `Hyperrealistic professional photograph of a Brazilian contemporary modern bathroom with mid-to-high-end market appeal. A vanity cabinet in MDF with white or light grey lacquer finish, matte or satin, with 2-4 flat straight doors and 2-3 stacked drawers on one side, slim flush-mounted handles (no visible handle) or brushed metal bar handles, integrated toeboard base — no visible feet. A white or light grey marble countertop with fine veining (Carrara or similar) or marbleized porcelain, with a 3cm visible edge thickness and a rectangular undermount white ceramic basin. A tall straight-spout single-lever faucet in matte black or brushed chrome, mounted on the countertop. A large rectangular mirror with slightly rounded corners and a thin champagne, rose gold, or matte black metal frame, centered above the vanity, covering most of the wall. No integrated shelf. A modern white toilet with straight-line coupled flush box design, positioned on the plumbing wall. Accessories: a matte black or stainless steel soap dispenser on the countertop, a beige or light grey folded hand towel on the vanity or on a brushed metal towel bar wall-mounted, a small slim vase with a eucalyptus or fern sprig on the countertop. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    popular_brasileiro: `Hyperrealistic professional photograph of a Brazilian popular-market bathroom staged with affordable standard fixtures. A compact vanity cabinet in white MDF/particleboard with standard popular market finish (no lacquer, no high-gloss) — 2 flat straight doors plus 1 central or upper drawer, simple chrome bar handles one per door, base with short visible feet or simple toeboard, 60-80cm width proportional to the bathroom. A white formica or simple white ceramic countertop with a white ceramic vessel basin (round or rectangular) positioned ON TOP of the countertop — not undermounted. A chrome single-lever faucet, basic standard model, mounted on the basin or countertop. A simple rectangular frameless mirror OR a mirror with small white MDF frame with a small lower shelf, standard size (50x70cm or similar), no rounded corners, no decorative frame. A standard white toilet with coupled flush box, basic model, positioned on the plumbing wall. A white plastic or white ceramic soap dispenser on the vanity. One folded white towel on a simple chrome towel rack wall-mounted. No candles, no diffusers, no plants. All furniture must be MDF/particleboard with standard popular market finish — no lacquer, no high-gloss, no premium materials. Hardware exclusively basic chrome. No granite, marble, or terrazzo countertops. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    minimalista_clean: `Hyperrealistic professional photograph of a Brazilian minimalist bathroom. Smooth polished grey concrete walls. A floating clean-lined cumaru wood vanity. A modern white ceramic vessel sink. A transparent frameless glass shower enclosure. Minimal matte black faucet fixtures. White towels folded and organized on a rack. A single small succulent plant. Sharp, clean geometric lines. Natural skylight lighting from above. Spa-like serene atmosphere. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    aconchegante_natural: `Hyperrealistic professional photograph of a Brazilian cozy natural bathroom. Warm beige travertine tiles on walls and floor. A wooden vanity with natural finish and soft lighting. A rounded white ceramic sink. Woven basket storage with rolled towels. Small plants on the counter. Warm sconce lighting with fabric shades. A natural fiber bath mat. Comfortable, warm, inviting spa atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    luxo_contemporaneo: `Hyperrealistic professional photograph of a Brazilian luxury contemporary bathroom. Large high-gloss white marble tiles on walls and floor. A floating white marble vanity with gold hardware. Modern-design gold faucet fixtures. A large mirror with integrated LED lighting. A frameless glass shower with marble interior. Luxury spa-quality white towels. Sophisticated, elegant atmosphere. Bright ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    industrial_urbano: `Hyperrealistic professional photograph of a Brazilian industrial urban bathroom. Raw grey-textured exposed concrete walls. A black metal vanity with concrete countertop. A white ceramic vessel sink. Industrial pipe shelving with towels. Matte black fixtures and hardware throughout. Edison bulb lighting above the mirror. White subway metro tiles in the shower area. Urban, edgy atmosphere. Natural lighting through a frosted window. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    boho_brasileiro: `Hyperrealistic professional photograph of a Brazilian boho bathroom. Colorful geometric-patterned cement tiles on the floor. A rustic wooden vanity with woven basket storage. A hand-painted ceramic sink with details. A round rattan mirror. Hanging and surface plants throughout. Colorful towels with tassels. Macrame accents. Relaxed, eclectic bohemian atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    classico_atemporal: `Hyperrealistic professional photograph of a Brazilian classic timeless bathroom. Traditional-layout white subway tiles on walls. A traditional mahogany vanity cabinet with marble countertop. A classic white porcelain pedestal sink. A traditional wood-framed mirror. Vintage-style brass fixtures. Classic hotel-style white towels. Elegant, traditional atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    rustico_brasileiro: `Hyperrealistic professional photograph of a Brazilian rustic bathroom. Pronounced-texture natural stone feature wall. A robust natural-finish cumaru wood vanity. An earthy-toned ceramic vessel sink. A rough-textured natural stone countertop. Matte black wrought iron fixtures. A reclaimed wood mirror frame. Earthy palette of brown, beige, and stone. Dominant textured materials. Warm, natural atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    colonial_brasileiro: `Hyperrealistic professional photograph of a Brazilian colonial-style bathroom. Traditional-pattern blue and white Portuguese azulejo ceramic tiles covering the walls. A carved-detail jacaranda wood vanity cabinet. A white classical marble countertop. Gold-finish vintage brass fixtures. An ornate carved wood framed mirror. White towels with lace details. Elegant classical proportions. Warm, traditional atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    contemporaneo_colorido: `Hyperrealistic professional photograph of a Brazilian contemporary colorful bathroom. White subway tile base walls. Vibrant-colored geometric terrazzo accent wall in the shower area. Modern gold faucet fixtures and hardware. Organized colorful yellow and blue ceramic accessories. A modern vanity with white marble countertop. A round geometric mirror. Playful, sophisticated atmosphere. Bright natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    japandi_brasileiro: `Hyperrealistic professional photograph of a Brazilian Japandi bathroom. Natural light wood tiles on floor and walls. A minimalist light-finish floating wooden vanity. A simple white ceramic vessel sink. A large frameless round mirror. Minimal matte black fixtures. Bamboo accents and plants. Rolled white towels. Zen spa wabi-sabi atmosphere. Soft diffused natural lighting. Neutral palette of wood and white. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    art_deco_brasileiro: `Hyperrealistic professional photograph of a Brazilian Art Deco bathroom. Black and white chevron-pattern geometric floor tiles. A black lacquer Art Deco vanity with brass details. An octagonal mirror with brass frame. Vintage Deco-style brass fixtures. A black marble countertop. Brass and frosted glass Art Deco wall sconces. Glamorous 1930s atmosphere. Warm ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    escandinavo_tropical: `Hyperrealistic professional photograph of a Brazilian Scandinavian tropical bathroom. Clean simple white wall tiles. A minimalist floating light wood vanity. An integrated white ceramic sink. Large tropical plants in the bathroom. A simple round mirror. Minimalist white fixtures. Simple white towels. Bright, airy hygge-tropical atmosphere. Abundant natural lighting through a frosted window. Palette of white, wood, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    neo_mediterraneo: `Hyperrealistic professional photograph of a Brazilian neo-Mediterranean bathroom. Smooth textured white plaster walls. Natural warm terracotta floor tiles. A traditional white ceramic pedestal sink. Blue Mediterranean ceramic accessories. A white-framed arched mirror. A natural fiber basket with towels. Coastal, relaxed atmosphere. Bright natural lighting. Palette of white, blue, and terracotta. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    urban_jungle: `Hyperrealistic professional photograph of a Brazilian urban jungle bathroom. Simple white wall tiles. A floating wooden vanity with plants on the counter. Multiple plants of various sizes on shelves and hanging. A botanical wallpaper accent wall. A white ceramic sink. Natural fiber accessories. A green, spa-like oasis atmosphere. Bright natural lighting filtered through plants. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // DINING ROOM
  // ─────────────────────────────────────────────────────────────────────────
  dining_room: {
    moderno_brasileiro: `Hyperrealistic professional photograph of a Brazilian contemporary modern dining room. Rich warm-toned ipe wood flooring. A centered oval organic-form wood dining table with glass insert. Sculptural curved leather and cane dining chairs around the table. A sculptural pendant light fixture above the table. A low-profile mid-century wood sideboard. An indoor-outdoor view with patio visible through windows. Abundant warm natural lighting. Sensual furniture curves. Inviting atmosphere. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    popular_brasileiro: `Hyperrealistic professional photograph of a Brazilian popular-market dining room staged with affordable standard furniture. A rectangular dining table with an 8mm tempered glass top on a white or black standard MDF/particleboard base. Four to six chairs upholstered in dark grey or black synthetic suede fabric with MDF/particleboard structure matching the table, simple chrome feet or handles. Optionally: a low buffet in white MDF/particleboard with 4 straight doors and chrome bar handles, or a standard display cabinet with glass shelves and doors, both in popular market standard. Optionally: a simple pendant light above the table, basic chrome or white model with a plastic or simple fabric shade. All furniture must be MDF/particleboard with standard popular market finish — no lacquer, no high-gloss, no premium materials. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    minimalista_clean: `Hyperrealistic professional photograph of a Brazilian minimalist dining room. Polished grey concrete accent wall. Natural cumaru wood floor. A centered minimal rectangular wood and glass dining table. Six modern clean-lined chairs around the table. A single centered geometric-design pendant light above the table. Very few decorative objects — ceramic vases only. Neutral palette of beige, grey, and white. Organized, clean space. Abundant natural lighting through windows. Serene atmosphere. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    aconchegante_natural: `Hyperrealistic professional photograph of a Brazilian cozy natural dining room. Warm honey-tone jatoba wood flooring. A centered round wooden dining table with natural finish. Comfortable beige linen upholstered chairs around the table. A warm pendant light with fabric shade above the table. A wooden sideboard with family photos. A natural-tone wool area rug under the table. Warm, homey, inviting atmosphere. Soft golden natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    luxo_contemporaneo: `Hyperrealistic professional photograph of a Brazilian luxury contemporary dining room. Large high-gloss white marble floor tiles. A centered designer white marble-top dining table. Elegant grey velvet upholstered chairs around the table. A modern crystal statement chandelier above the table. Large abstract art on the wall. A contemporary gold metal sideboard. Sophisticated, elegant atmosphere. Bright natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    industrial_urbano: `Hyperrealistic professional photograph of a Brazilian industrial urban dining room. Exposed brick accent wall. Polished grey concrete floor. A centered industrial reclaimed wood dining table with metal legs. Black metal chairs with wood seats around the table. Industrial Edison bulb pendant lights above the table. Metal shelving with dishes and plants. Large windows with black metal frames. Urban, edgy atmosphere. Natural lighting through industrial windows. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    boho_brasileiro: `Hyperrealistic professional photograph of a Brazilian boho dining room. Natural light wood flooring. A rustic wooden dining table with mix-and-match colorful chairs. Woven rattan chairs. A pendant light in woven natural fibers above the table. A colorful ethnic-patterned table runner. Plants on the sideboard and hanging. A macrame wall hanging. Relaxed, eclectic bohemian atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    classico_atemporal: `Hyperrealistic professional photograph of a Brazilian classic timeless dining room. Polished dark espresso wood flooring. A centered traditional rectangular mahogany dining table. Beige upholstered dining chairs with carved wood details around the table. A traditional brass and crystal chandelier above the table. A traditional mahogany sideboard cabinet. A traditional-pattern area rug in muted colors. Elegant, understated, formal atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    rustico_brasileiro: `Hyperrealistic professional photograph of a Brazilian rustic dining room. Terracotta exposed brick accent wall. A centered massive reclaimed cumaru solid wood dining table. Robust wooden chairs with leather seats around the table. A centered black wrought iron chandelier above the table. A reclaimed wood buffet cabinet. Dominant earthy palette of brown, terracotta, and beige. Pronounced textured materials. Warm, inviting, cozy atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    colonial_brasileiro: `Hyperrealistic professional photograph of a Brazilian colonial-style dining room. A centered large traditional rectangular jacaranda wood dining table. Six symmetrically positioned cane-back dining chairs around the table. Blue and white Portuguese azulejo ceramic tiles on the buffet feature wall. A traditional carved wood buffet cabinet. A centered classical crystal chandelier above the table. Elegant, balanced classical proportions. Dominant warm dark wood tones. Inviting, formal atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    contemporaneo_colorido: `Hyperrealistic professional photograph of a Brazilian contemporary colorful dining room. Bright white base walls. A centered modern white marble-top dining table. Vibrant-colored upholstered dining chairs in a mix of yellow, blue, and orange around the table. A modern gold metal pendant light above the table. Bold colorful Brazilian art on the wall. A modern-design geometric sideboard. Eclectic, sophisticated atmosphere. Abundant bright natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    japandi_brasileiro: `Hyperrealistic professional photograph of a Brazilian Japandi dining room. Natural light cumaru wood flooring. A centered minimalist low-profile wooden dining table. Simple clean-lined wooden chairs around the table. A single paper lantern pendant light above the table. A minimal low wooden sideboard. A single statement monstera plant in the corner. Neutral palette of beige, grey, and wood. Zen, calm, serene atmosphere. Soft diffused natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    art_deco_brasileiro: `Hyperrealistic professional photograph of a Brazilian Art Deco dining room. Dark wood Art Deco-pattern geometric parquet flooring. A centered black lacquer dining table with brass inlay details. Emerald green velvet dining chairs with brass legs around the table. A geometric brass and frosted glass chandelier above the table. A mirrored Art Deco sideboard with brass trim. Geometric mirror wall decoration. Glamorous 1930s atmosphere. Warm ambient lighting from Art Deco fixtures. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    escandinavo_tropical: `Hyperrealistic professional photograph of a Brazilian Scandinavian tropical dining room. White-washed light ash wood flooring. A centered simple light-finish wooden dining table. Simple white Scandinavian-design chairs around the table. A simple minimal white pendant light above the table. Large tropical plants in the corners. Bright white walls. A minimalist light wood sideboard. Airy hygge atmosphere with tropical plants. Abundant natural lighting. Palette of white, wood, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    neo_mediterraneo: `Hyperrealistic professional photograph of a Brazilian neo-Mediterranean dining room. Smooth plaster white textured walls. Natural terracotta floor tiles. A centered weathered white-finish wooden dining table. Simple white chairs with blue cushions around the table. A white and blue ceramic pendant light above the table. A visible arched doorway. Natural woven placemats. Coastal, relaxed, vacation atmosphere. Abundant bright natural lighting. Palette of white, blue, and terracotta. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    urban_jungle: `Hyperrealistic professional photograph of a Brazilian urban jungle dining room. Natural light wood flooring. A simple wooden dining table with a plant centerpiece. Modern grey chairs around the table. Abundant plants of various sizes on shelves and floor. Hanging plants above the table area. Botanical prints on the walls. A natural fiber rug under the table. A green dining oasis atmosphere. Bright natural lighting through plants. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // KITCHEN
  // ─────────────────────────────────────────────────────────────────────────
  kitchen: {
    moderno_brasileiro: `Hyperrealistic professional photograph of a Brazilian contemporary modern kitchen with mid-to-high-end market appeal. Fitted modular cabinets in medium grey matte MDF (urban grey) with flush-mounted integrated handles (no visible handle) or slim brushed metal handles. Structure and details in wood laminate (freijo or light oak). Complete configuration: upper wall cabinets with flat grey matte doors close to the ceiling, with an open niche clad in wood laminate with recessed LED strip lighting on the underside displaying small decorative objects; lower base cabinets with grey matte doors and drawers with integrated or slim handles; a tall pantry tower integrated into the set in grey matte. A white or light grey marble countertop with fine veining (Carrara marble or similar) or marbleized porcelain — premium appearance, 3-4cm visible edge thickness. Backsplash in white marble or marbleized porcelain matching the countertop — no colorful tiles. Appliances: a French-door or side-by-side refrigerator in brushed stainless steel positioned at the side or end of the cabinets; a 4-5 burner gas cooktop built into the countertop in stainless steel; a built-in microwave or electric oven in a dedicated cabinet niche in stainless steel or black; a slim range hood or exhaust above the cooktop in stainless steel or black. Accessories: two or three decorative objects in the wood niche — small vases, cookbooks, or glass jars with spices; a slim vase with a green sprig on the countertop; do not overcrowd the scene. Aesthetic of a planned kitchen in a decorated model apartment from a mid-to-high-end Brazilian developer. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    popular_brasileiro: `Hyperrealistic professional photograph of a Brazilian popular-market kitchen staged with affordable standard cabinetry. A complete set of modular kitchen cabinets in MDF/particleboard, standard popular market finish (no lacquer, no high-gloss). Choose the option that best harmonizes with the existing walls and floor: Option A — White with relief-panel doors (more traditional/popular): all doors (base cabinets, upper wall cabinets, and tall pantry) in white MDF with decorative relief panel, curved line motif with diamond detail in the center, chrome bar handles, stainless steel or light grey laminate countertop, backsplash in colorful Portuguese tiles (blue, yellow, and white) or plain white tile. Option B — Freijo wood-tone plus matte black (more modern popular): doors in standard matte black MDF (no lacquer) with structure and sides in freijo laminate (MDF with wood laminate, not solid wood), chrome or brushed nickel bar handles, freijo laminate countertop (wood-tone formica), background: white wall or plain white tile. Mandatory appliances for both options: a standard white frost-free refrigerator positioned at one end of the cabinet set; a white countertop or niche microwave; a white 4-burner floor-standing stove with oven, positioned in the cooking area if visible. Accessories: a small vase with a simple plant or basic flowers on the countertop; do not overcrowd the scene. All cabinets must be MDF/particleboard standard popular — no lacquer, no high-gloss, no premium materials. Consistent handles throughout the kitchen (all chrome OR all brushed nickel, never mixed). No marble or natural stone countertops. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    minimalista_clean: `Hyperrealistic professional photograph of a Brazilian minimalist kitchen. Smooth polished grey concrete floor. White matte handleless floating cabinets. An ultra-thin white quartz countertop with integrated sink. Exposed concrete ceiling detail. Minimal black matte faucet hardware and fixtures. A single succulent plant on the windowsill. A simple geometric pendant light. Sharp, clean, organized lines. Soft diffused natural lighting. Neutral palette of white and grey. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    aconchegante_natural: `Hyperrealistic professional photograph of a Brazilian cozy natural kitchen. Warm honey-tone light oak wood flooring. Natural-finish shaker-style wood cabinets. A honed beige granite countertop with warm texture. A warm-pattern terracotta tile backsplash. Vintage-style brass fixtures. Woven baskets on storage shelves. Potted herbs on the windowsill. Warm pendant lights with fabric shades. Comfortable, homey, inviting atmosphere. Soft golden natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    luxo_contemporaneo: `Hyperrealistic professional photograph of a Brazilian luxury contemporary kitchen. Polished dark grey large-format porcelain floor tiles. Floor-to-ceiling dark grey matte cabinets. A white Calacatta marble countertop with dramatic veining. Premium-finish gold hardware and fixtures. A modern sculptural statement chandelier. Integrated panel-ready high-end appliances. A visible wine cooler. Sophisticated, elegant atmosphere. Bright ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    industrial_urbano: `Hyperrealistic professional photograph of a Brazilian industrial urban kitchen. Red terracotta exposed brick accent wall. Polished grey concrete floor. Black metal cabinets with open shelving. Industrial-finish concrete countertop. White subway tiles in brick-pattern backsplash. Matte black fixtures and hardware throughout. Hanging Edison bulb pendant lights. Exposed stainless steel appliances. Urban, edgy atmosphere. Natural lighting through large windows. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    boho_brasileiro: `Hyperrealistic professional photograph of a Brazilian boho kitchen. Natural light wood flooring. Olive green painted lower base cabinets. Upper open wood shelving with colorful dishes. A colorful Moroccan-patterned cement tile backsplash. A warm butcher-block wooden countertop. Vintage brass fixtures. Woven natural fiber pendant lights. Various plants, hanging and on the counter. Relaxed, eclectic bohemian atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    classico_atemporal: `Hyperrealistic professional photograph of a Brazilian classic timeless kitchen. Polished dark espresso wood flooring. Traditional-design white shaker-style cabinets. A polished black granite countertop. A classic white subway tile backsplash. Elegant vintage brass hardware. Traditional pendant lights with glass shades. A white porcelain farmhouse sink. Elegant, understated atmosphere. Warm soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    rustico_brasileiro: `Hyperrealistic professional photograph of a Brazilian rustic kitchen. Natural-texture reclaimed cumaru wood flooring. Natural-texture reclaimed demolition wood cabinets. A dark grey soapstone (pedra-sabao) natural stone countertop. A terracotta exposed brick backsplash. Aged-patina copper fixtures and hardware. A hanging wrought iron pot rack. Visible wooden ceiling beams. Earthy palette of brown, stone, and copper. Pronounced textured materials. Warm, cozy atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    colonial_brasileiro: `Hyperrealistic professional photograph of a Brazilian colonial-style kitchen. Rich-finish dark jacaranda wood flooring. Traditional carved-detail jacaranda wood cabinets. An elegant veined white marble countertop. Traditional blue and white Portuguese azulejo tile backsplash. Vintage colonial gold brass fixtures. A small classical crystal chandelier. Carved wood details on the island. Warm, inviting traditional atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    contemporaneo_colorido: `Hyperrealistic professional photograph of a Brazilian contemporary colorful kitchen. Large-format white porcelain floor tiles. Modern navy blue matte-finish cabinets. A white terrazzo countertop with colorful aggregate. Modern brushed gold hardware. Vibrant-pattern colorful geometric backsplash tiles. Modern-design gold pendant lights. Organized colorful yellow and blue accessories. Playful, sophisticated atmosphere. Bright natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    japandi_brasileiro: `Hyperrealistic professional photograph of a Brazilian Japandi kitchen. Natural blonde light ash wood flooring. Minimal handleless floating light wood cabinets. A matte-finish beige stone countertop. A simple white tile backsplash. Minimalist matte black fixtures. A few wabi-sabi-style ceramic pieces. Bamboo cutting boards. A single plant in the corner. Zen, calm, clean atmosphere. Soft diffused natural lighting. Neutral palette of wood and beige. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    art_deco_brasileiro: `Hyperrealistic professional photograph of a Brazilian Art Deco kitchen. Dark wood geometric-pattern parquet flooring. High-gloss black lacquer cabinets with gold trim. A black marble countertop with gold veining. A black, white, and gold geometric-pattern tile backsplash. Vintage Art Deco-design brass fixtures. Brass and frosted glass geometric pendant lights. Gold hardware throughout. Glamorous, sophisticated 1930s atmosphere. Warm ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    escandinavo_tropical: `Hyperrealistic professional photograph of a Brazilian Scandinavian tropical kitchen. White-washed light ash wood flooring. Simple clean Scandinavian-design white cabinets. A minimalist light wood countertop. A simple white subway tile backsplash. Minimalist white fixtures. Tropical plants on the windowsill and counter. Simple minimal white pendant lights. Airy hygge atmosphere with tropical plants. Abundant bright natural lighting. Palette of white, wood, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    neo_mediterraneo: `Hyperrealistic professional photograph of a Brazilian neo-Mediterranean kitchen. Smooth white textured plaster walls. Natural warm terracotta floor tiles. White shaker-style painted cabinets. A textured white gesso countertop. Blue Mediterranean-pattern ceramic tile backsplash. Decorative blue ceramic accessories. Weathered-finish wooden open shelving. Coastal, relaxed, vacation-vibe atmosphere. Abundant bright natural lighting. Palette of white, blue, and terracotta. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    urban_jungle: `Hyperrealistic professional photograph of a Brazilian urban jungle kitchen. Natural light wood flooring. Dark green matte-finish lower cabinets. Upper open wood shelving filled with plants. A simple white countertop. A white subway tile backsplash. Abundant plants on the counter and hanging in various sizes. Botanical prints on the walls. Wooden cutting boards and natural accessories. A lush green oasis atmosphere. Bright natural lighting filtered through plants. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OFFICE / HOME OFFICE
  // ─────────────────────────────────────────────────────────────────────────
  office: {
    moderno_brasileiro: `Hyperrealistic professional photograph of a Brazilian contemporary modern home office with mid-to-high-end market appeal. A wide desk with a white MDF lacquer or wood-laminate top (freijo or light oak), 3-4cm visible edge thickness, on matte black or brushed steel metal legs. A separate pedestal drawer unit with 3-4 drawers in white or light grey MDF lacquer with slim brushed metal or flush-mounted handles, on casters for mobility. A high-back ergonomic chair in dark grey or black mesh or fabric, upholstered seat, chrome or polished aluminum base with casters — contemporary slim design without excessive bulk. If wall space is available: a fitted shelf unit in MDF combining open niches and closed modules with swing doors in white or grey lacquer, slim brushed metal handles, ceiling height, open niches with color-organized books, small vases, and decorative objects. A flat-screen monitor on the desk (one or two monitors), slim keyboard and wireless mouse, a metal monitor arm or stand, a discreet cable management box under the desk. A desk lamp articulated with a base or clamp, in matte black or gold metal, positioned at one corner of the desktop. Optionally: a suspended pendant over the desk with a metal arm and minimalist shade. A small plant in a white ceramic or concrete pot on the desk or shelf. An abstract framed artwork on the wall behind the desk. Metal or concrete pen holder and desk accessories. Organized books. Aesthetic of a planned home office in a decorated model apartment from a mid-to-high-end Brazilian developer. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    popular_brasileiro: `Hyperrealistic professional photograph of a Brazilian popular-market home office staged with affordable standard furniture. A rectangular desk in white or black standard MDF/particleboard with standard market finish (no lacquer, no high-gloss), simple model with a flat top, optionally with one lateral drawer or a separate MDF pedestal drawer unit. Simple chrome bar handles. A swivel executive office chair with high backrest, upholstered in black fabric or faux leather, black plastic or chrome metal base with casters, basic model with height adjustment. Optionally if space allows: a simple bookshelf in white MDF/particleboard with 3-5 open shelves, with organized books and one or two basic decorative objects. OR a tall cabinet in white MDF with 2 straight doors and chrome bar handles. A flat-screen desktop monitor on the desk (basic model), keyboard and mouse on the desktop. Do not overcrowd the scene with too many objects. All furniture must be MDF/particleboard with standard popular market finish — no lacquer, no high-gloss, no premium materials or designer brands. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    minimalista_clean: `Hyperrealistic professional photograph of a Brazilian minimalist home office. Polished grey concrete floor. A floating white wall-mounted desk with clean lines. A minimalist black ergonomic mesh chair. A concrete accent wall behind the desk. Minimal white floating shelves with very few objects. A single succulent plant on the desk. A black geometric desk lamp. A large window with sheer curtains. Organized, clean workspace. Soft natural lighting. Neutral palette of white, grey, and black. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    aconchegante_natural: `Hyperrealistic professional photograph of a Brazilian cozy natural home office. Warm honey-tone jatoba wood flooring. A solid natural-finish wood desk with drawers. A comfortable beige fabric upholstered desk chair. A floor-to-ceiling wood bookshelf filled with books. A natural-tone wool area rug under the desk. A warm fabric-shade desk lamp. Plants on shelves and the desk. A window with linen curtains. Warm, inviting, productive atmosphere. Soft golden natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    luxo_contemporaneo: `Hyperrealistic professional photograph of a Brazilian luxury contemporary home office. Dark marble-effect large-format porcelain floor tiles. A modern black lacquer desk with gold accents. A sophisticated black tufted leather executive chair. A black marble accent wall behind the desk. Floating shelves with gold brackets and art books. A modern sculptural gold statement desk lamp. A large abstract canvas art piece. Floor-to-ceiling windows with a city view. Sophisticated, professional atmosphere. Bright ambient lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    industrial_urbano: `Hyperrealistic professional photograph of a Brazilian industrial urban home office. Full-wall exposed brick accent wall. Polished grey concrete floor. An industrial reclaimed wood desk with metal pipe legs. A vintage distressed brown leather desk chair. Black metal shelving units with books and boxes. Hanging Edison bulb pendant lights. Vintage metal file cabinets. A large window with a black metal frame. Urban, edgy, productive atmosphere. Natural lighting through industrial windows. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    boho_brasileiro: `Hyperrealistic professional photograph of a Brazilian boho home office. Natural light wood flooring. A simple wood trestle-style desk. A natural woven rattan desk chair with a cushion. A large macrame wall hanging behind the desk. Open wood shelving with colorful books and plants. Woven storage baskets. A colorful patterned layered rug. Various hanging plants. Decorative warm string lights. Relaxed, creative, bohemian atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    classico_atemporal: `Hyperrealistic professional photograph of a Brazilian classic timeless home office. Polished mahogany dark wood flooring. A traditional mahogany desk with carved details and leather inset top. A classic dark brown tufted leather desk chair. A floor-to-ceiling built-in wood bookshelf with a ladder. A traditional brass desk lamp with a green glass shade. A traditional Persian-pattern area rug. Subtle white wall moldings. Elegant, formal, professional atmosphere. Warm natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    rustico_brasileiro: `Hyperrealistic professional photograph of a Brazilian rustic home office. Natural-texture reclaimed cumaru wood flooring. A massive reclaimed cumaru solid wood desk with iron legs. A rustic aged brown leather desk chair. A natural-texture stone accent wall behind the desk. Asymmetric reclaimed wood shelving with books. A matte black wrought iron desk lamp. Earthy palette of brown, stone, and iron. Dominant textured materials. Warm, cozy, productive atmosphere. Soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    colonial_brasileiro: `Hyperrealistic professional photograph of a Brazilian colonial-style home office. Traditional dark jacaranda wood flooring. An ornate carved-detail antique jacaranda writing desk. An elegant colonial-style cane-back desk chair. A carved jacaranda built-in bookshelf with glass doors. A blue and white Portuguese azulejo tile feature wall. A small classical brass chandelier. Framed religious art on the wall. Warm, traditional, professional atmosphere. Warm soft natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    contemporaneo_colorido: `Hyperrealistic professional photograph of a Brazilian contemporary colorful home office. Clean bright white walls. A modern white desk with organized colorful accessories. A vibrant yellow modern ergonomic desk chair. A bold geometric colorful abstract mural on the wall behind the desk. White floating shelves with colorful books. A modern gold desk lamp. A geometric-pattern colorful area rug. Playful, creative, inspiring atmosphere. Bright natural lighting. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    japandi_brasileiro: `Hyperrealistic professional photograph of a Brazilian Japandi home office. Natural blonde light cumaru wood flooring. A minimalist clean-lined light-finish wood desk. A natural wood wishbone chair with beige cushion. Very few decorative objects. A minimal floating wood shelf with a bonsai plant. A soft-glow paper lantern desk lamp. A tatami-inspired mat under the desk. Sheer white curtains at a large window. Zen, calm, wabi-sabi productive atmosphere. Soft diffused natural lighting. Neutral palette of beige and wood. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    art_deco_brasileiro: `Hyperrealistic professional photograph of a Brazilian Art Deco home office. Dark wood chevron-pattern geometric parquet flooring. A black lacquer desk with gold geometric inlay in Art Deco style. An emerald green velvet desk chair with brass legs. A geometric brass and glass bookshelf. A brass Art Deco desk lamp with a geometric frosted glass shade. A sunburst gold-frame geometric mirror. Rich jewel tones of black, green, and gold. Glamorous, sophisticated 1930s atmosphere. Warm ambient lighting from Art Deco fixtures. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    escandinavo_tropical: `Hyperrealistic professional photograph of a Brazilian Scandinavian tropical home office. White-washed light ash wood flooring. A simple white minimalist Scandinavian-design desk. A clean modern white ergonomic chair. A white pegboard wall organization system with plants. Tropical plants of various sizes on the desk and floor. Bright white walls. A simple minimal white desk lamp. Airy, hygge, productive atmosphere with a tropical touch. Abundant soft natural lighting. Palette of white, wood, and green. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    neo_mediterraneo: `Hyperrealistic professional photograph of a Brazilian neo-Mediterranean home office. Smooth white textured plaster walls. Natural warm terracotta floor tiles. A simple weathered white-finish wooden desk. A simple white chair with a blue cushion. White floating shelves with books. Decorative blue ceramic accessories. A natural woven storage basket. An arched window with sheer curtains. Coastal, relaxed, productive atmosphere. Abundant bright natural lighting. Palette of white, blue, and terracotta. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,

    urban_jungle: `Hyperrealistic professional photograph of a Brazilian urban jungle home office. Natural light wood flooring. A simple wood desk with plants integrated on the surface. A modern grey ergonomic desk chair. Abundant large plants of various sizes on the desk, shelves, and hanging. Botanical prints and living walls. Natural wood shelving filled with plants and books. A lush, inspiring green workspace oasis atmosphere. Bright natural lighting filtered through plant leaves. Palette of wood, green, and white. The image must be absolutely hyperrealistic — indistinguishable from a real photograph taken with a professional DSLR camera with perfect natural lighting, shadows, reflections, and depth of field. Ultra high resolution, 4k.`,
  },
}
