import { POPULAR_BRASILEIRO_PROMPTS, MODERNO_BRASILEIRO_PROMPTS } from './prompt-library-popular.js'

export const PROMPT_LIBRARY = {
  living_room: {
    moderno_brasileiro: MODERNO_BRASILEIRO_PROMPTS.living_room,
    minimalista_clean: "photograph of Brazilian minimalist living room, concrete exposed ceiling polished smooth, cumaru wood floor planks natural finish, large grey sectional sofa clean lines positioned 40cm from walls, white marble coffee table rectangular centered, minimal TV console cumaru wood floating, few decorative objects ceramic vases white, single monstera plant in corner ceramic pot, sheer white curtains floor-to-ceiling windows, abundant natural lighting soft, neutral palette beige grey white, organized serene space, high resolution, highly detailed, 4k",
    aconchegante_natural: "photograph of Brazilian cozy natural living room, warm wood flooring jatoba honey tones, comfortable beige linen sofa with throw pillows textured, wooden coffee table natural finish with books, plush area rug wool cream under furniture, warm lighting table lamps with fabric shades, indoor plants various sizes ceramic pots, wooden shelving with family photos, soft curtains natural linen, warm inviting atmosphere homey, natural lighting soft golden, high resolution, highly detailed, 4k",
    luxo_contemporaneo: "photograph of Brazilian luxury contemporary living room, large format porcelain tiles marble effect white, designer sectional sofa grey velvet sophisticated, black marble coffee table with gold metal base, statement chandelier modern sculptural design, abstract art large canvas colorful, gold metal accent furniture details, floor-to-ceiling windows with sheer curtains, sophisticated elegant atmosphere, abundant natural lighting bright, high-end finishes visible, high resolution, highly detailed, 4k",
    industrial_urbano: "photograph of Brazilian industrial urban living room, exposed brick wall red terracotta texture, polished concrete floor grey, distressed leather sofa brown vintage positioned center, reclaimed wood coffee table with metal legs industrial, metal shelving black with books and plants, Edison bulb pendant lights hanging, vintage metal factory chair accent, large windows with black frames, urban edgy atmosphere, natural lighting through industrial windows, high resolution, highly detailed, 4k",
    boho_brasileiro: "photograph of Brazilian boho living room, light wood flooring natural, rattan sectional sofa with colorful cushions ethnic patterns, low wooden coffee table moroccan style, layered rugs with geometric patterns colorful, macramé wall hanging large, abundant plants various sizes hanging and floor, woven baskets storage, warm string lights decorative, eclectic mix textures colors, relaxed bohemian atmosphere, natural lighting warm, high resolution, highly detailed, 4k",
    classico_atemporal: "photograph of Brazilian classic timeless living room, dark wood flooring espresso finish polished, elegant sofa beige linen fabric with rolled arms, mahogany coffee table traditional design centered, classic armchairs upholstered symmetrical, traditional area rug persian style muted colors, wall moldings white subtle, classic table lamps with fabric shades, elegant understated atmosphere, warm natural lighting soft, high resolution, highly detailed, 4k",
    rustico_brasileiro: "photograph of Brazilian rustic living room, exposed brick wall accent terracotta color, cumaru wood ceiling beams natural finish visible, large solid wood sofa brown leather cushions robust, reclaimed wood coffee table massive centered, wrought iron floor lamp corner, natural stone feature wall texture pronounced, earthy palette brown beige terracotta, textured materials dominant, warm inviting cozy atmosphere, natural lighting soft, handcrafted furniture quality, high resolution, highly detailed, 4k",
    colonial_brasileiro: "photograph of Brazilian colonial style living room, jacaranda wood furniture dark rich finish, cane back armchairs Austrian style positioned symmetrically, solid wood coffee table carved details, Portuguese ceramic tiles azulejos blue white on feature wall, classical proportions balanced elegant, carved wood console table with religious art framed above, lioz stone doorway arch visible, warm dark wood tones dominant, traditional atmosphere inviting, natural lighting warm, high resolution, highly detailed, 4k",
    contemporaneo_colorido: "photograph of Brazilian contemporary colorful living room, white marble floor with terrazzo geometric inserts, modern grey sectional sofa clean base, vibrant throw pillows yellow orange emerald blue arranged, gold metal side table accent, Brazilian abstract art on walls colorful bold, geometric pattern area rug under coffee table, eclectic mix modern furniture and classic Brazilian pieces, white walls bright, sophisticated playful atmosphere, abundant natural lighting, high resolution, highly detailed, 4k",
    japandi_brasileiro: "photograph of Brazilian japandi living room, light cumaru wood flooring natural blonde tone, low profile sofa beige linen clean lines, minimalist wooden coffee table low with subtle grain, tatami-inspired area rug natural fibers, single statement plant monstera large ceramic pot, sheer curtains white floor-to-ceiling, wabi-sabi ceramics few pieces, zen calm atmosphere serene, soft diffused natural lighting, neutral palette beige grey green, high resolution, highly detailed, 4k",
    art_deco_brasileiro: "photograph of Brazilian art deco living room, geometric parquet flooring chevron pattern dark wood, velvet sofa emerald green with gold metal legs, octagonal marble coffee table with brass details, geometric mirror sunburst design gold frame, brass floor lamp with frosted glass shade, art deco wallpaper geometric pattern subtle, rich jewel tones emerald navy gold, glamorous sophisticated atmosphere 1940s inspired, warm ambient lighting, high resolution, highly detailed, 4k",
    escandinavo_tropical: "photograph of Brazilian scandinavian tropical living room, light wood flooring ash white washed, white linen sofa simple clean lines, light wood coffee table minimalist design, abundant tropical plants monstera banana leaf various sizes, white walls bright, natural fiber rug jute beige, simple pendant light white, airy open atmosphere hygge meets tropical, abundant natural lighting bright, neutral warm palette white beige green, high resolution, highly detailed, 4k",
    neo_mediterraneo: "photograph of Brazilian neo-mediterranean living room, white textured walls stucco finish, terracotta floor tiles natural, white linen sofa with blue striped cushions, light wood coffee table weathered finish, arched doorway visible white, ceramic vases blue white mediterranean, woven baskets natural, sheer white curtains billowing, relaxed coastal atmosphere vacation vibes, bright natural lighting abundant, palette white blue terracotta, high resolution, highly detailed, 4k",
    urban_jungle: "photograph of Brazilian urban jungle living room, light wood flooring natural, modern grey sofa simple base, abundant plants filling space various sizes monstera fiddle leaf fern hanging, plant stands various heights wood and metal, botanical prints on walls, natural fiber rug jute, macramé plant hangers, green oasis atmosphere lush, bright natural lighting through plants, palette grey green white natural, high resolution, highly detailed, 4k",
    popular_brasileiro: POPULAR_BRASILEIRO_PROMPTS.living_room
  },
  bedroom: {
    moderno_brasileiro: MODERNO_BRASILEIRO_PROMPTS.bedroom,
    minimalista_clean: "photograph of Brazilian minimalist bedroom, concrete accent wall behind bed polished grey, cumaru wood platform bed low profile centered, white linen bedding texture clean, minimal wooden nightstands floating symmetrical, pendant lights simple geometric design hanging, sheer white curtains windows, neutral palette beige grey white, few decorative objects only, calm serene atmosphere peaceful, soft natural lighting, organized clean space, high resolution, highly detailed, 4k",
    aconchegante_natural: "photograph of Brazilian cozy natural bedroom, warm jatoba wood flooring honey tone, upholstered headboard beige linen texture soft, wooden nightstands natural finish with table lamps warm light, layered bedding cream beige with knit throw blanket, plush area rug wool under bed, indoor plants on nightstand, warm ambient lighting soft, comfortable inviting atmosphere homey, natural lighting soft golden, high resolution, highly detailed, 4k",
    luxo_contemporaneo: "photograph of Brazilian luxury contemporary bedroom, large format porcelain tiles white marble effect, upholstered bed frame grey velvet tufted headboard king size, marble nightstands white with gold hardware, crystal table lamps with white shades, luxurious bedding white with gold accent pillows, statement chandelier modern design, abstract art above headboard, sophisticated elegant atmosphere, soft ambient lighting, high resolution, highly detailed, 4k",
    industrial_urbano: "photograph of Brazilian industrial urban bedroom, exposed brick accent wall behind bed, polished concrete floor grey, metal bed frame black with wood headboard reclaimed, industrial metal nightstands with Edison bulb lamps, grey bedding linen texture simple, metal floating shelves with books, large window with black metal frame, urban edgy atmosphere, natural lighting through industrial window, high resolution, highly detailed, 4k",
    boho_brasileiro: "photograph of Brazilian boho bedroom, light wood flooring natural, low platform bed with colorful textiles layered, macramé headboard wall hanging large, rattan nightstands with warm lighting, layered rugs colorful patterns, plants hanging and on surfaces various, dreamcatcher and ethnic textiles decorative, warm string lights ambient, relaxed bohemian atmosphere eclectic, soft natural lighting warm, high resolution, highly detailed, 4k",
    classico_atemporal: "photograph of Brazilian classic timeless bedroom, dark wood flooring polished espresso, upholstered bed beige linen with classic tufted headboard, mahogany nightstands traditional carved details, classic table lamps with fabric shades, elegant bedding white with subtle embroidery, area rug traditional pattern muted colors, wall moldings white subtle, elegant understated atmosphere, soft natural lighting warm, high resolution, highly detailed, 4k",
    rustico_brasileiro: "photograph of Brazilian rustic bedroom, reclaimed cumaru wood accent wall natural texture behind bed, solid wood platform bed robust natural finish centered, linen bedding natural beige tones textured, wrought iron wall sconces symmetrical, natural stone side table rough texture, earthy palette brown terracotta beige, warm cozy atmosphere inviting, textured materials pronounced visible, soft natural lighting warm, high resolution, highly detailed, 4k",
    colonial_brasileiro: "photograph of Brazilian colonial style bedroom, jacaranda wood four-poster bed carved details centered, cane bedside tables traditional design symmetrical, carved wood headboard ornate classical, Portuguese lace bedding white delicate, religious art framed above headboard, warm dark wood tones dominant, classical chandelier small above bed, traditional elegant atmosphere, warm natural lighting soft, high resolution, highly detailed, 4k",
    contemporaneo_colorido: "photograph of Brazilian contemporary bedroom colorful, white walls base clean, upholstered headboard grey fabric textured, vibrant throw pillows yellow blue emerald arranged bed, colorful Brazilian art above headbed bold geometric, gold metal nightstands modern design, geometric pattern area rug small under bed, eclectic mix modern furniture, playful sophisticated atmosphere, bright natural lighting, high resolution, highly detailed, 4k",
    japandi_brasileiro: "photograph of Brazilian japandi bedroom, light cumaru flooring natural blonde, low platform bed minimalist with beige linen bedding, floating wooden nightstands light wood minimal, paper lantern pendant lights soft glow, single monstera plant in corner, tatami-inspired mat beside bed, sheer curtains white, zen calm atmosphere wabi-sabi, soft diffused natural lighting, neutral palette beige grey, high resolution, highly detailed, 4k",
    art_deco_brasileiro: "photograph of Brazilian art deco bedroom, geometric parquet flooring dark wood herringbone, velvet upholstered bed navy blue with brass details, geometric nightstands mirrored with brass trim, art deco table lamps brass with frosted glass, luxurious bedding jewel tones with geometric patterns, geometric wallpaper accent wall gold silver, glamorous 1940s atmosphere sophisticated, warm ambient lighting art deco fixtures, high resolution, highly detailed, 4k",
    escandinavo_tropical: "photograph of Brazilian scandinavian tropical bedroom, light ash wood flooring white washed, simple platform bed light wood with white linen bedding, minimal wooden nightstands light finish, tropical plants monstera and palm on nightstand, white walls bright clean, simple pendant light white minimal, airy hygge atmosphere with tropical touch, abundant natural lighting soft, palette white beige green, high resolution, highly detailed, 4k",
    neo_mediterraneo: "photograph of Brazilian neo-mediterranean bedroom, white textured walls smooth plaster, terracotta floor tiles natural warm, white linen bed with blue accent pillows, light weathered wood nightstands, ceramic table lamps blue white, arched window with sheer white curtains, woven basket storage, relaxed coastal vacation atmosphere, bright natural lighting soft, palette white blue terracotta, high resolution, highly detailed, 4k",
    urban_jungle: "photograph of Brazilian urban jungle bedroom, light wood flooring natural, simple platform bed grey with white bedding, abundant plants surrounding bed various sizes, plant stands beside bed with monstera, botanical prints above headboard, hanging plants macramé holders, natural fiber rug jute, green sanctuary atmosphere lush peaceful, bright natural lighting filtered through plants, high resolution, highly detailed, 4k",
    popular_brasileiro: POPULAR_BRASILEIRO_PROMPTS.bedroom
  },
  bathroom: {
    moderno_brasileiro: MODERNO_BRASILEIRO_PROMPTS.bathroom,
    minimalista_clean: "photograph of Brazilian minimalist bathroom, polished concrete walls grey smooth, cumaru wood vanity floating clean lines, white ceramic vessel sink modern, frameless glass shower enclosure transparent, minimal matte black fixtures faucet, white towels folded on rack organized, small succulent plant single, clean geometric lines sharp, natural skylight lighting from above, spa-like serene atmosphere, high resolution, highly detailed, 4k",
    aconchegante_natural: "photograph of Brazilian cozy natural bathroom, warm beige travertine tiles walls and floor, wooden vanity natural finish with soft lighting, white ceramic sink rounded, woven basket storage with rolled towels, plants on counter small, warm lighting sconces with fabric shades, natural fiber bath mat, comfortable spa atmosphere warm inviting, soft natural lighting, high resolution, highly detailed, 4k",
    luxo_contemporaneo: "photograph of Brazilian luxury contemporary bathroom, large white marble tiles walls floor high gloss, floating vanity white marble with gold hardware, gold faucet fixtures modern design, large mirror with integrated LED lighting, frameless glass shower with marble interior, white towels luxury spa quality, sophisticated elegant atmosphere, bright ambient lighting, high resolution, highly detailed, 4k",
    industrial_urbano: "photograph of Brazilian industrial urban bathroom, exposed concrete walls raw grey texture, black metal vanity with concrete countertop, white vessel sink ceramic, industrial pipe shelving with towels, matte black fixtures and hardware, Edison bulb lighting above mirror, metro tiles white subway in shower, urban edgy atmosphere, natural lighting through frosted window, high resolution, highly detailed, 4k",
    boho_brasileiro: "photograph of Brazilian boho bathroom, cement tiles colorful geometric patterns floor, wooden vanity rustic with woven basket storage, ceramic sink hand-painted details, rattan mirror round, plants hanging and on surfaces, colorful towels with tassels, macramé accents, relaxed bohemian atmosphere eclectic, warm natural lighting, high resolution, highly detailed, 4k",
    classico_atemporal: "photograph of Brazilian classic timeless bathroom, white subway tiles walls traditional layout, mahogany vanity cabinet traditional with marble countertop, classic pedestal sink white porcelain, framed mirror traditional wood frame, brass fixtures vintage style, white towels classic hotel style, elegant traditional atmosphere, soft natural lighting, high resolution, highly detailed, 4k",
    rustico_brasileiro: "photograph of Brazilian rustic bathroom, natural stone wall feature texture pronounced, cumaru wood vanity natural finish robust, ceramic vessel sink earthy tone, natural stone countertop rough texture, wrought iron fixtures black matte, wooden mirror frame reclaimed wood, earthy palette brown beige stone, textured materials dominant, warm natural atmosphere, soft lighting natural, high resolution, highly detailed, 4k",
    colonial_brasileiro: "photograph of Brazilian colonial style bathroom, Portuguese ceramic tiles azulejos blue white covering walls traditional pattern, jacaranda wood vanity cabinet carved details, classical marble countertop white, vintage brass fixtures gold finish, framed mirror ornate carved wood, white towels with lace details, classical proportions elegant, warm traditional atmosphere, natural lighting soft, high resolution, highly detailed, 4k",
    contemporaneo_colorido: "photograph of Brazilian contemporary bathroom colorful, white subway tiles base walls, terrazzo accent wall shower area vibrant colors geometric, gold fixtures modern faucet hardware, colorful ceramic accessories yellow blue organized, modern vanity white marble countertop, geometric mirror round, playful sophisticated atmosphere, bright natural lighting, high resolution, highly detailed, 4k",
    japandi_brasileiro: "photograph of Brazilian japandi bathroom, light wood tiles floor and walls natural, floating wooden vanity minimalist light finish, white ceramic vessel sink simple, large round mirror frameless, matte black fixtures minimal, bamboo accents and plants, white towels rolled, zen spa atmosphere wabi-sabi, soft diffused natural lighting, neutral palette wood white, high resolution, highly detailed, 4k",
    art_deco_brasileiro: "photograph of Brazilian art deco bathroom, black white geometric tiles floor chevron pattern, art deco vanity black lacquer with brass details, geometric mirror octagonal with brass frame, brass fixtures vintage deco style, black marble countertop, art deco sconces brass and frosted glass, glamorous 1930s atmosphere, warm ambient lighting, high resolution, highly detailed, 4k",
    escandinavo_tropical: "photograph of Brazilian scandinavian tropical bathroom, white tiles walls clean simple, light wood vanity floating minimalist, white ceramic sink integrated, large plants in bathroom tropical, simple round mirror, white fixtures minimalist, white towels simple, bright airy atmosphere hygge tropical, abundant natural lighting through frosted window, palette white wood green, high resolution, highly detailed, 4k",
    neo_mediterraneo: "photograph of Brazilian neo-mediterranean bathroom, white plaster walls textured smooth, terracotta tiles floor natural warm, white ceramic pedestal sink traditional, blue ceramic accessories mediterranean, arched mirror white frame, natural fiber basket with towels, coastal relaxed atmosphere, bright natural lighting, palette white blue terracotta, high resolution, highly detailed, 4k",
    urban_jungle: "photograph of Brazilian urban jungle bathroom, white tiles walls simple, floating wooden vanity with plants on counter, multiple plants various sizes on shelves and hanging, botanical wallpaper accent wall, white ceramic sink, natural fiber accessories, green oasis atmosphere spa-like, bright natural lighting filtered through plants, high resolution, highly detailed, 4k",
    popular_brasileiro: POPULAR_BRASILEIRO_PROMPTS.bathroom
  },
  dining_room: {
    moderno_brasileiro: "photograph of Brazilian modernism dining room, ipê wood flooring rich warm tones, oval dining table organic form wood with glass insert centered, sculptural dining chairs curved leather and cane design around table, pendant light fixture sculptural design above table, low sideboard profile wood mid-century, indoor-outdoor view patio visible through windows, warm natural lighting abundant, sensual curves furniture, inviting atmosphere, high resolution, highly detailed, 4k",
    minimalista_clean: "photograph of Brazilian minimalist dining room, concrete accent wall polished grey, cumaru wood floor natural, minimal rectangular dining table wood and glass centered, six modern chairs clean lines around table, single pendant light geometric design above table centered, few decorative objects ceramic vases only, neutral palette beige grey white, organized clean space, natural lighting abundant through windows, serene atmosphere, high resolution, highly detailed, 4k",
    aconchegante_natural: "photograph of Brazilian cozy natural dining room, warm jatoba wood flooring honey tone, round wooden dining table natural finish centered, upholstered chairs beige linen comfortable around table, warm pendant light with fabric shade above table, wooden sideboard with family photos, area rug wool natural tones under table, warm inviting atmosphere homey, natural lighting soft golden, high resolution, highly detailed, 4k",
    luxo_contemporaneo: "photograph of Brazilian luxury contemporary dining room, large white marble floor tiles high gloss, designer dining table white marble top centered, velvet upholstered chairs grey elegant around table, statement chandelier crystal modern design above table, abstract art large on wall, gold metal sideboard contemporary, sophisticated elegant atmosphere, bright natural lighting, high resolution, highly detailed, 4k",
    industrial_urbano: "photograph of Brazilian industrial urban dining room, exposed brick wall accent, polished concrete floor grey, industrial dining table reclaimed wood with metal legs centered, metal chairs black with wood seats around table, industrial pendant lights Edison bulbs above table, metal shelving with dishes and plants, large windows with black metal frames, urban edgy atmosphere, natural lighting through industrial windows, high resolution, highly detailed, 4k",
    boho_brasileiro: "photograph of Brazilian boho dining room, light wood flooring natural, wooden dining table rustic with mix-match chairs colorful, rattan chairs woven design, pendant light woven natural fibers above table, colorful runner table with ethnic pattern, plants on sideboard and hanging, macramé wall hanging, relaxed bohemian atmosphere eclectic, warm natural lighting, high resolution, highly detailed, 4k",
    classico_atemporal: "photograph of Brazilian classic timeless dining room, dark wood flooring espresso polished, mahogany dining table rectangular traditional centered, upholstered dining chairs beige with carved wood details around table, traditional chandelier brass and crystal above table, mahogany sideboard cabinet traditional, area rug traditional pattern muted colors, elegant understated atmosphere formal, warm natural lighting, high resolution, highly detailed, 4k",
    rustico_brasileiro: "photograph of Brazilian rustic dining room, exposed brick wall terracotta accent, massive solid wood dining table reclaimed cumaru centered, robust wooden chairs leather seats around table, wrought iron chandelier black above table centered, wooden buffet cabinet reclaimed wood storage, earthy palette brown terracotta beige dominant, textured materials pronounced, warm inviting cozy atmosphere, natural lighting soft, high resolution, highly detailed, 4k",
    colonial_brasileiro: "photograph of Brazilian colonial style dining room, large jacaranda wood dining table rectangular centered traditional, cane back dining chairs six positioned around table symmetrically, Portuguese ceramic tiles azulejos blue white on buffet wall feature, carved wood buffet cabinet traditional storage, crystal chandelier classical above table centered, classical proportions elegant balanced, warm dark wood tones dominant, inviting formal atmosphere, natural lighting warm, high resolution, highly detailed, 4k",
    contemporaneo_colorido: "photograph of Brazilian contemporary dining room colorful, white walls bright base, modern dining table white marble top centered, upholstered dining chairs vibrant colors yellow blue orange mix around table, gold metal pendant light modern above table, Brazilian art colorful on wall bold, geometric sideboard modern design, eclectic sophisticated atmosphere, abundant natural lighting bright, high resolution, highly detailed, 4k",
    japandi_brasileiro: "photograph of Brazilian japandi dining room, light cumaru wood flooring natural, minimalist wooden dining table low profile centered, simple wooden chairs clean lines around table, single pendant light paper lantern above table, low wooden sideboard minimal, single statement plant monstera in corner, neutral palette beige grey wood, zen calm atmosphere serene, soft diffused natural lighting, high resolution, highly detailed, 4k",
    art_deco_brasileiro: "photograph of Brazilian art deco dining room, geometric parquet flooring dark wood art deco pattern, dining table black lacquer with brass inlay details centered, velvet dining chairs emerald green with brass legs around table, geometric chandelier brass and frosted glass above table, art deco sideboard mirrored with brass trim, geometric mirror wall decoration, glamorous 1930s atmosphere, warm ambient lighting art deco fixtures, high resolution, highly detailed, 4k",
    escandinavo_tropical: "photograph of Brazilian scandinavian tropical dining room, light ash wood flooring white washed, simple wooden dining table light finish centered, white chairs simple Scandinavian design around table, simple pendant light white minimal above table, tropical plants large in corners, white walls bright, light wood sideboard minimalist, airy hygge atmosphere with tropical plants, abundant natural lighting, palette white wood green, high resolution, highly detailed, 4k",
    neo_mediterraneo: "photograph of Brazilian neo-mediterranean dining room, white textured walls plaster smooth, terracotta floor tiles natural, wooden dining table weathered white finish centered, white chairs simple with blue cushions around table, ceramic pendant light white blue above table, arched doorway visible, woven placemats natural, coastal relaxed atmosphere vacation, bright natural lighting abundant, palette white blue terracotta, high resolution, highly detailed, 4k",
    urban_jungle: "photograph of Brazilian urban jungle dining room, light wood flooring natural, simple wooden dining table with plants centerpiece, modern chairs grey around table, abundant plants on shelves and floor various sizes, hanging plants above table area, botanical prints on walls, natural fiber rug under table, green dining oasis atmosphere, bright natural lighting through plants, high resolution, highly detailed, 4k",
    popular_brasileiro: POPULAR_BRASILEIRO_PROMPTS.dining_room
  },
  kitchen: {
    moderno_brasileiro: MODERNO_BRASILEIRO_PROMPTS.kitchen,
    minimalista_clean: "photograph of Brazilian minimalist kitchen, white flat-front cabinets handle-free, quartz countertop white seamless, integrated stainless appliances flush, open shelving minimal ceramics, clean geometric lines, neutral palette white grey, natural lighting abundant, organized serene space, high resolution, highly detailed, 4k",
    popular_brasileiro: POPULAR_BRASILEIRO_PROMPTS.kitchen
  },
  office: {
    moderno_brasileiro: POPULAR_BRASILEIRO_PROMPTS.office_moderno,
    popular_brasileiro: POPULAR_BRASILEIRO_PROMPTS.office
  }
}
